RequestMapping codemod
pixee/codemodder-java pull request #142
Opened 2023-08-17 19:36 UTC by danielostrow

Codemod created for migrating RequestMapping to GetMapping on verbose cases.

There is a potential need to do similar changes that can be added in for

- PostMapping
- PutMapping
- DeleteMapping
- PatchMapping

2023-08-21 21:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/pixee/codemodder-java?pullRequest=142) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/pixee/codemodder-java?pullRequest=142) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/pixee/codemodder-java?pullRequest=142) it.</sub>

2023-08-21 22:41 UTC, danielostrow commented on core-codemods/src/main/java/io/codemodder/codemods/VerboseRequestMappingCodemod.java
> +
`NormalAnnotationExpr` allowed me to identify individual pairs within the set when there are more than one pairs. I was using this response on stack overflow. https://stackoverflow.com/questions/37208935/javaparser-annotationexpr-get-parameters

2023-08-24 03:19 UTC, nahsra commented on core-codemods/src/main/java/io/codemodder/codemods/VerboseRequestMappingCodemod.java
> +
This method (and type) should just ask for this normal thing subtype instead of just AnnotationExpr if we only want the subtype, right?

2023-08-24 03:24 UTC, nahsra requested changes

2023-08-24 03:24 UTC, nahsra commented on core-codemods/src/main/resources/io/codemodder/codemods/VerboseRequestMappingCodemod/description.md
> +The [composed annotations](https://dzone.com/articles/using-the-spring-requestmapping-annotation) better express the semantics of the annotated methods. They act as wrapper to@RequestMapping and have
Typo?

2023-08-24 13:47 UTC, nahsra commented on core-codemods/src/main/resources/io/codemodder/codemods/VerboseRequestMappingCodemod/description.md
> +    - Identifies `@RequestMapping` annotations where the HTTP method is undefined.
Is that true? I'm not sure if that's true. I thought it would support all HTTP methods if it's not explicit about the method.

2023-08-24 13:59 UTC, danielostrow commented on core-codemods/src/main/resources/io/codemodder/codemods/VerboseRequestMappingCodemod/description.md
> +    - Identifies `@RequestMapping` annotations where the HTTP method is undefined.
It was not true, I made the changes correcting that. My mistake.

2023-08-24 16:16 UTC, danielostrow commented on core-codemods/src/main/java/io/codemodder/codemods/VerboseRequestMappingCodemod.java
> +
From what I currently understand about javaparser, I was able to specify a key pair to remove within an `AnnotationExpr` with `NormalAnnotationExpr`; but, I needed to make use of `AnnotationExpr.setName("...")` to change the annotation name after the key pair was removed.

2023-08-24 16:35 UTC, danielostrow commented on core-codemods/src/main/resources/io/codemodder/codemods/verbose-request-mapping.yaml
> +            @RequestMapping(method = RequestMethod.GET,...)
Thats a good point, playing around in the sandbox I made these changes:

```
rules:
  - id: verbose-request-mapping
    patterns:
      - pattern-either:
        - pattern: |
            @RequestMapping(method = $REQUEST_METHOD, ...)
        - pattern: |
            @RequestMapping(method = $VALUE, ...)
    message: Semgrep found a match.
    languages: [java]
    severity: WARNING
    ```

2023-08-24 16:36 UTC, danielostrow commented on core-codemods/src/main/resources/io/codemodder/codemods/VerboseRequestMappingCodemod/description.md
> +The [composed annotations](https://dzone.com/articles/using-the-spring-requestmapping-annotation) better express the semantics of the annotated methods. They act as wrapper to@RequestMapping and have
Edited.

2023-08-24 17:47 UTC, nahsra commented on core-codemods/src/main/resources/io/codemodder/codemods/VerboseRequestMappingCodemod/description.md
> +This change simplifies spring framework annotations by making use of shortened annotations when applicable.
Should probably be "Spring Framework", not "spring framework"

2023-08-24 17:50 UTC, nahsra commented on core-codemods/src/test/resources/verbose-request-mapping/Test.java.before
> +    @NonsenseMapping(value = "/example6", method = RequestMethod.GET)
This is not what I meant. I meant `@RequestMethod.NONSENSE`, but this is a fine test too I guess

2023-08-24 17:53 UTC, nahsra commented on core-codemods/src/main/resources/io/codemodder/codemods/VerboseRequestMappingCodemod/description.md
> +This change simplifies spring framework annotations by making use of shortened annotations when applicable.
I want a sentence here that completes the thought towards why we're suggesting this change.

 "Code that is easy to read is easy to review, reason about, and detect bugs in. We believe this change makes the code much easier to read."

2023-08-24 18:03 UTC, nahsra commented on core-codemods/src/main/resources/io/codemodder/codemods/VerboseRequestMappingCodemod/report.json
> +  "summary": "Since version 4.3, Springframework has introduced shortcut annotation types specific to a requested http method.",
This doesn't sound like the other `summary` fields, check out others and revisit.

2023-08-24 18:04 UTC, nahsra requested changes
Almost there!

2023-08-24 19:58 UTC, danielostrow commented on core-codemods/src/test/resources/verbose-request-mapping/Test.java.before
> +    @NonsenseMapping(value = "/example6", method = RequestMethod.GET)
edited.

2023-08-24 20:02 UTC, danielostrow commented on core-codemods/src/main/resources/io/codemodder/codemods/VerboseRequestMappingCodemod/report.json
> +  "summary": "Since version 4.3, Springframework has introduced shortcut annotation types specific to a requested http method.",
edited.

2023-08-24 20:03 UTC, danielostrow commented on core-codemods/src/main/resources/io/codemodder/codemods/VerboseRequestMappingCodemod/report.json
> +  "change": "Improved readability and conciseness by making use of the shortcut annotations for the requested http method.",
corrected.

2023-08-25 00:39 UTC, nahsra approved these changes

2023-08-25 05:16 UTC, merged