Work on files outside of traditional source directories
pixee/codemodder-java pull request #160
Opened 2023-08-30 17:42 UTC by nahsra

This change allows us to transform files that are not inside traditional source directories. There appears to be no downside tradeoffs, except that they will have weaker symbol resolution capabilities.

2023-08-30 18:42 UTC, ryandens requested changes
Overall LGTM but the integration test is failing so not sure what changes are needed to get it working properly

2023-08-30 18:42 UTC, ryandens commented on framework/codemodder-base/src/main/java/io/codemodder/CLI.java
> +            .forEach(allFiles::add);
```suggestion
      final List<Path> allFiles;
      try (Stream<Path> paths = Files.walk(projectDir)) {
        allFiles = paths
            .filter(Files::isRegularFile)
            .filter(p -> !Files.isSymbolicLink(p)) // could cause infinite loop if we follow links
            .filter(p -> includesExcludes.shouldInspect(p.toFile()))
            .sorted()
            .toList();
```

Lets use `Stream.toList()` inside the try-with-resources rather than creating a list and adding to it inside a `forEach`

2023-08-30 18:42 UTC, ryandens commented on framework/codemodder-base/src/main/java/io/codemodder/CLI.java
> +            .forEach(allFiles::add);
chatgpt prompts to get this, because I looked at it and thought it was a bit odd:

> how to use Files.walk java api properly  

outputted something very similar to what you have here

> How can I see Files.walk and the Stream Collect API

Gave what i suggested

2023-08-31 00:41 UTC, nahsra commented on framework/codemodder-base/src/test/java/io/codemodder/CLITest.java
> +     * Only add module2 to the discovered source directories. This will help prove that the module2 files can still be seen and changed, even if we couldn't locate it as a "source directory".
Yes, derp

2023-08-31 00:44 UTC, nahsra commented
> Overall LGTM but the integration test is failing so not sure what changes are needed to get it working properly

Amazing, this produced 2 unexpected changes, both positive. First, it allowed us to modify the root `pom.xml` and inject the dependencies we need all the way up, which is what was happening locally before a few weeks ago when we were facing the last-second `pom-operator` issues. 

Second, it found new files to change in the `.mvn` directory, which I guess is some dynamically generated stuff, maybe for `mvnw`? I added a change to make sure that's excluded by default.

<img width="797" alt="image" src="https://github.com/pixee/codemodder-java/assets/911610/9c996469-ffac-4c77-b29d-eef993a4f753">

2023-08-31 00:55 UTC, nahsra commented
> > Overall LGTM but the integration test is failing so not sure what changes are needed to get it working properly
> 
> Amazing, this produced 2 unexpected changes, both positive. First, it allowed us to modify the root `pom.xml` and inject the dependencies we need all the way up, which is what was happening locally before a few weeks ago when we were facing the last-second `pom-operator` issues.
> 
> Second, it found new files to change in the `.mvn` directory, which I guess is some dynamically generated stuff, maybe for `mvnw`? I added a change to make sure that's excluded by default. I'm adding tests for this.
> 
> <img alt="image" width="797" src="https://user-images.githubusercontent.com/911610/264503644-9c996469-ffac-4c77-b29d-eef993a4f753.png">

Too bad: ignoring the `.mvn` directory caused us to not alter the root `pom.xml` file, so looks that will continue to be imperfect. But, good validation that we really will scan Java files anywhere now.

2023-08-31 03:48 UTC, nahsra commented
Ready for re-review

2023-08-31 17:32 UTC, ryandens approved these changes
:shipit: Nice!

2023-08-31 23:46 UTC, merged