Adding POM-Operator code to Codemodder repository
pixee/codemodder-java pull request #192
Opened 2023-10-11 19:48 UTC by carlosu7

Bringing [POM-OPERATOR java source code migration](https://github.com/pixee/pom-operator/pull/37) classes to Codemodder project.

Also [POM-Operator java tests from this branch](https://github.com/carlosu7/pom-operator/pull/4) were added to codemodder repo

Basically what I did was:

* Moved POM-Operator java source code to `plugins/codemodder-plugin-maven/src/main/java/io.codemodder.plugins.maven.operator` 
* Moved POM-Operator java tests to `plugins/codemodder-plugin-maven/src/test/java/io.codemodder.plugins.maven.operator`
* Moved POM-Operator xml test resources to `plugins/codemodder-plugin-maven/src/test/resources/io.codemodder.plugins.maven.operator`. 
* Update `plugins/codemodder-plugin-maven/build.gradle.kts` to add pom-operator dependencies

2023-10-11 19:48 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/pixee/codemodder-java?pullRequest=192) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/pixee/codemodder-java?pullRequest=192) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/pixee/codemodder-java?pullRequest=192) it.</sub>

2023-10-11 20:05 UTC, carlosu7 commented
@aldrinleal when I was locally running tests for pom-operator, I was not able to run `POMOperatorJavaIT.java` successfully, but with `act -j build` it runs successfully. With that said, when I'm locally running `./gradlew check` for codemodder, `POMOperatorJavaIT` keeps failing.

2023-10-11 20:17 UTC, nahsra requested changes
Can you take at removing `public` everywhere it's not needed? Without this, it will be a little hard to work on the monorepo because of all these new classes being visible everywhere.

Whatever APIs need to be `public` after that, let's add JavaDoc to them. There's a lot of other cleanup we can do, but it can wait. My main concern is adding 100+ new public Java classes to the project.

2023-10-11 20:17 UTC, nahsra commented on plugins/codemodder-plugin-maven/java-sample/src/test/java/io/github/pixee/it/POMOperatorJavaTest.java
> +
We should make all the tests package-protected and `final`

2023-10-11 20:17 UTC, nahsra commented on plugins/codemodder-plugin-maven/src/main/java/io/codemodder/plugins/maven/operator/AbstractCommand.java
> +
While you have good context here on these, can you add JavaDoc?

2023-10-11 20:17 UTC, nahsra commented on plugins/codemodder-plugin-maven/src/main/java/io/codemodder/plugins/maven/operator/AbstractQueryCommand.java
> +
JavaDoc

Does it need to be `public`?

2023-10-11 20:17 UTC, nahsra commented on plugins/codemodder-plugin-maven/src/main/java/io/codemodder/plugins/maven/operator/AbstractQueryCommand.java
> +  protected abstract void extractDependencyTree(File outputPath, File pomFilePath, ProjectModel c);
JavaDoc

2023-10-11 20:17 UTC, nahsra commented on plugins/codemodder-plugin-maven/src/main/java/io/codemodder/plugins/maven/operator/AbstractVersionCommand.java
> +public class AbstractVersionCommand extends AbstractCommand {
JavaDoc

2023-10-11 20:17 UTC, nahsra commented on plugins/codemodder-plugin-maven/src/main/java/io/codemodder/plugins/maven/operator/AbstractVersionCommand.java
> +  public Set<VersionDefinition> result = new TreeSet<>(VERSION_KIND_COMPARATOR);
Does this need to be `public`?

2023-10-11 20:17 UTC, nahsra commented on plugins/codemodder-plugin-maven/src/main/java/io/codemodder/plugins/maven/operator/Chain.java
> +public class Chain {
This class name is too generic, what's it a chain of? I think `CommandChain` makes sense.

2023-10-11 22:13 UTC, aldrinleal commented
> @aldrinleal @nahsra I tag you here since I'm not able to add reviewers to this PR
> 
> @aldrinleal when I was locally running tests for pom-operator, I was not able to run `POMOperatorJavaIT.java` successfully, but with `act -j build` it runs successfully. With that said, when I'm locally running `./gradlew check` for codemodder, `POMOperatorJavaIT` keeps failing.
> 
> Also, I wonder if content inside`plugins/codemodder-plugin-maven/java-sample/src` is needed. I see that `plugins/codemodder-plugin-maven/java-sample/pom.xml` is needed for `POMOperatorJavaIT.java`

`POMOperatorJavaIT` was a safe-measure (or another canary, just like the `-result.xml` files) to ensure it was able to be consumed from plain Java. You can safely delete that since its on the same codebase after all.

2023-10-13 16:36 UTC, nahsra approved these changes

2023-10-13 16:36 UTC, merged