Remove version from Dependency hash code for assertion purposes
pixee/codemodder-java pull request #214
Opened 2023-10-26 19:43 UTC by carlosu7

Also I updated assertions library

Ticket: https://www.notion.so/pixee/POMOperatorMultipomTest-fails-because-dependency-version-are-set-to-UNKNOWN-301698310bf64497b0f2f7d8e6524d62?pvs=4

2023-10-26 20:11 UTC, nahsra requested changes

2023-10-26 20:11 UTC, nahsra commented on plugins/codemodder-plugin-maven/src/main/java/io/codemodder/plugins/maven/operator/Dependency.java
>    public int hashCode() {
This feels wrong. I feel the contract for `hashCode` should be different if the `version` is different. If we have to make another method somewhere, like, `matchesWithoutConsideringVersion()`, then we should add that. But, I would look hard at that code.

2023-10-26 20:11 UTC, nahsra commented on plugins/codemodder-plugin-maven/src/test/java/io/codemodder/plugins/maven/operator/POMOperatorMultipomTest.java
> -          File parentResource = getResource("parent-and-child-parent-broken.xml");
I would definitely prefer to `import static` these methods so they're easier to read.

2023-10-26 20:11 UTC, nahsra commented on plugins/codemodder-plugin-maven/src/test/java/io/codemodder/plugins/maven/operator/POMOperatorMultipomTest.java
> +                  Arrays.asList(POMDocumentFactory.load(parentResource));
Does `spotless` run on this module?

2023-10-26 20:11 UTC, nahsra commented on plugins/codemodder-plugin-maven/src/test/java/io/codemodder/plugins/maven/operator/POMOperatorMultipomTest.java
>    void testWithParentAndChildWrongType() {
These names don't really "tell the story" of the test they want to perform. Can we add some "human" descriptions (via JavaDoc) of the use case they are intended to support? Adding this kind of context to the code with comments is definitely part of bringing this module into the repo as it will make it much easier to maintain.

2023-10-26 20:11 UTC, nahsra commented on plugins/codemodder-plugin-maven/src/test/java/io/codemodder/plugins/maven/operator/POMOperatorMultipomTest.java
I like this change. Nothing to stdout!

2023-10-26 20:51 UTC, carlosu7 commented on plugins/codemodder-plugin-maven/src/test/java/io/codemodder/plugins/maven/operator/POMOperatorMultipomTest.java
> +                  Arrays.asList(POMDocumentFactory.load(parentResource));
I have run `./gradlew :plugins:codemodder-plugin-maven:spotlessApply` and it applies changes, does it mean yes???

2023-11-01 18:35 UTC, nahsra commented on plugins/codemodder-plugin-maven/src/test/java/io/codemodder/plugins/maven/operator/POMOperatorMultipomTest.java
> +                  Arrays.asList(POMDocumentFactory.load(parentResource));
I mean when i just run `./gradlew spotlessApply` from the root, does it affect this module? If not, we should add it.

2023-11-01 18:36 UTC, nahsra commented on plugins/codemodder-plugin-maven/src/test/java/io/codemodder/plugins/maven/operator/POMOperatorMultipomTest.java
> +   * @throws Exception If there is an exception during the test.
We can just check not offer these `@throws` comments for tests

2023-11-01 18:37 UTC, nahsra commented on plugins/codemodder-plugin-maven/src/main/java/io/codemodder/plugins/maven/operator/Dependency.java
JavaDoc

2023-11-01 18:37 UTC, nahsra commented on plugins/codemodder-plugin-maven/src/main/java/io/codemodder/plugins/maven/operator/Dependency.java
> +
JavaDoc

2023-11-01 18:37 UTC, nahsra approved these changes
I approved, but please fix the outstanding tasks

2023-11-01 18:51 UTC, carlosu7 commented on plugins/codemodder-plugin-maven/src/test/java/io/codemodder/plugins/maven/operator/POMOperatorMultipomTest.java
> +                  Arrays.asList(POMDocumentFactory.load(parentResource));
it does 👍

2023-11-01 19:19 UTC, merged