Initial refactor
pixee/codemodder-java pull request #225
Opened 2023-11-06 20:11 UTC by carlosu7

Remove public accessors to the following classes:
* Command
* Kind
* QueryType
* SupportCommand

Refactor ProjectModelFactory::withQueryType to withSafeQueryType and always set quertyType to QueryType.SAFE

Remove POMScanner::legacyScanFrom

2023-11-10 13:30 UTC, nahsra commented
@carlosu7 can we fix the SonarCloud warning?

2023-11-10 18:44 UTC, nahsra commented on plugins/codemodder-plugin-maven/src/main/java/io/codemodder/plugins/maven/operator/POMScanner.java
>     */
Should we add anther ticket/task along the way to convert `File` -> `Path`?

2023-11-10 18:46 UTC, nahsra commented on plugins/codemodder-plugin-maven/src/test/java/io/codemodder/plugins/maven/operator/POMOperatorVersionQueryTest.java
> +    Optional<VersionQueryResponse> optionalVersionQueryResponse = null;
We can collapse these:

```
catch (ExceptionType1 | ExceptionType2 | ExceptionType3 e) {
 ...
}
```

2023-11-10 18:47 UTC, carlosu7 commented on plugins/codemodder-plugin-maven/src/main/java/io/codemodder/plugins/maven/operator/POMScanner.java
>     */
Ticket created

2023-11-10 18:47 UTC, nahsra commented on plugins/codemodder-plugin-maven/src/test/java/io/codemodder/plugins/maven/operator/POMOperatorVersionQueryTest.java
> +  @Test
On second thought, why are we catching any of these? Just let them propagate and fail the test.

2023-11-10 18:48 UTC, nahsra commented on plugins/codemodder-plugin-maven/src/test/java/io/codemodder/plugins/maven/operator/POMOperatorVersionQueryTest.java
> +    Optional<VersionQueryResponse> optionalVersionQueryResponse = null;
Just propagate

2023-11-10 18:48 UTC, nahsra requested changes
Just propagate the exception failures

2023-11-10 19:09 UTC, carlosu7 commented
@nahsra exceptions propagated except the ones that are inside lambda functions, in those cases i collapsed them

2023-11-13 19:26 UTC, nahsra approved these changes

2023-11-13 19:32 UTC, merged