Command chain to insert only a dependency
pixee/codemodder-java pull request #232
Opened 2023-11-14 22:04 UTC by carlosu7

2023-11-14 23:19 UTC, carlosu7 commented on plugins/codemodder-plugin-maven/src/main/java/io/codemodder/plugins/maven/operator/FormatCommand.java
> +        xmlRepresentation =
this change was to handle a index out of bounds exception

2023-11-14 23:29 UTC, nahsra requested changes

2023-11-14 23:29 UTC, nahsra commented on plugins/codemodder-plugin-maven/src/test/java/io/codemodder/plugins/maven/operator/POMOperatorTest.java
> +    Assert.assertTrue("Original POM File is Dirty", !context.getPomFile().getDirty());
This logic is weird, can we write it so it's not a double negative?
```suggestion
    Assert.assertFalse("Original POM File is Dirty", context.getPomFile().getDirty());
```

2023-11-14 23:29 UTC, nahsra commented on plugins/codemodder-plugin-maven/src/main/java/io/codemodder/plugins/maven/operator/FormatCommand.java
> +        xmlRepresentation =
Is there a regression test for this?

2023-11-14 23:33 UTC, carlosu7 commented on plugins/codemodder-plugin-maven/src/test/java/io/codemodder/plugins/maven/operator/POMOperatorTest.java
> +    Assert.assertTrue("Original POM File is Dirty", !context.getPomFile().getDirty());
it is weird... i got confused at some point while i was having some issues

2023-11-15 00:21 UTC, carlosu7 commented on plugins/codemodder-plugin-maven/src/main/java/io/codemodder/plugins/maven/operator/FormatCommand.java
> +        xmlRepresentation =
i removed this condition to validate where the exception was thrown and write a test but it is not being thrown... It happened at the beginning of my research but it got fixed at some point during development process

2023-11-15 14:39 UTC, nahsra approved these changes

2023-11-15 18:10 UTC, merged