Rename tests
pixee/codemodder-java pull request #234
Opened 2023-11-16 00:30 UTC by carlosu7

test names from `testThingDoesThing`() to `it_handles_failures_gracefully`()

2023-11-16 05:49 UTC, nahsra requested changes

2023-11-16 05:49 UTC, nahsra commented on plugins/codemodder-plugin-maven/src/test/java/io/codemodder/plugins/maven/operator/POMOperatorMultipomTest.java
>    @Test
What does the wrong dependency "type" mean, in this context?

2023-11-16 05:49 UTC, nahsra commented on plugins/codemodder-plugin-maven/src/test/java/io/codemodder/plugins/maven/operator/POMOperatorVersionQueryTest.java
>      Assert.assertFalse(
Can we static import `assertFalse` so we can make these easier to read? I don't want to scope creep too much, so can we add a separate PR/issue for making these all use assertj to match the other tests in the project as well?

2023-11-16 05:49 UTC, nahsra commented on plugins/codemodder-plugin-maven/src/test/java/io/codemodder/plugins/maven/operator/POMScannerTest.java
>    @Test
Oh man, can we capture some Java comments for these tests while you have the context? It's so not clear to me what these do, and now is the best time to add them IMO. If you want, you can make it a separate PR.

2023-11-16 05:49 UTC, nahsra commented on plugins/codemodder-plugin-maven/src/test/java/io/codemodder/plugins/maven/operator/UtilForTests.java
I'd probably call this `POMs` or something, `UtilForTests` is kind of weird.

2023-11-16 20:59 UTC, carlosu7 commented on plugins/codemodder-plugin-maven/src/test/java/io/codemodder/plugins/maven/operator/POMOperatorMultipomTest.java
>    @Test
added to WrongDependencyTypeException javadoc

2023-11-16 21:13 UTC, nahsra commented on plugins/codemodder-plugin-maven/src/test/java/io/codemodder/plugins/maven/operator/POMOperatorTest.java
> +   * @throws Exception if an error occurs during the test.
Can take out all these because they're kind of obvious

2023-11-16 21:13 UTC, nahsra commented on plugins/codemodder-plugin-maven/src/test/java/io/codemodder/plugins/maven/operator/POMOperatorTest.java
> +   * @throws Exception if an error occurs during the test.
(the `@throws Exception` comments)

2023-11-17 01:30 UTC, nahsra approved these changes

2023-11-17 05:42 UTC, merged