Sonar codemod to remove redundant variable creation expression
pixee/codemodder-java pull request #253
Opened 2023-12-04 21:33 UTC by carlosu7

Given example: https://sonarcloud.io/project/issues?cleanCodeAttributeCategories=INTENTIONAL&resolved=false&id=nahsra_WebGoat_10_23&open=AYvtrj5QLCzGLicz7AqQ&tab=code

Sonar rule reference: https://rules.sonarsource.com/java/RSPEC-1488/

2023-12-04 21:58 UTC, carlosu7 commented on core-codemods/src/main/resources/io/codemodder/codemods/RemoveRedundantVariableCreationCodemod/description.md
> +TODO
@nahsra you're better at this than me u.u

2023-12-05 00:26 UTC, nahsra requested changes

2023-12-05 00:26 UTC, nahsra commented on core-codemods/src/main/java/io/codemodder/codemods/RemoveRedundantVariableCreationCodemod.java
> +    if (blockStmtOpt.isPresent()) {
This logic doesn't feel right to me. This will always return `true`, even in a situation where no changes were made.

2023-12-05 00:26 UTC, nahsra commented on core-codemods/src/main/java/io/codemodder/codemods/RemoveRedundantVariableCreationCodemod.java
> +      final Optional<Statement> lastStmtOpt =
This logic feels shakey too. If we know for certain the one we're looking for is always the last statement, why don' we call `blockStmt.getStatements().get(size)` to get it? This filtering seems like a weird way to find what we know we can find by looking at the end, right?

2023-12-05 00:26 UTC, nahsra commented on core-codemods/src/main/java/io/codemodder/codemods/RemoveRedundantVariableCreationCodemod.java
> +            final Expression expression = objectCreationExpr.clone();
Hmm, why `clone()`? I've never had to invoke this, so I'm curious. I wonder if this will retain the concrete syntax (spacing) of the original node.

2023-12-05 00:26 UTC, nahsra commented on core-codemods/src/main/resources/io/codemodder/codemods/RemoveRedundantVariableCreationCodemod/description.md
> +TODO
```
This change removes intermediate variables who are only created to be thrown or returned in the next statement. This makes the code more readable, which makes reviewing the code for issues easier.
```

2023-12-05 00:36 UTC, carlosu7 commented on core-codemods/src/main/java/io/codemodder/codemods/RemoveRedundantVariableCreationCodemod.java
> +      final Optional<Statement> lastStmtOpt =
since it is sorted, yes, i didn't considered that

2023-12-05 00:39 UTC, carlosu7 commented on core-codemods/src/main/java/io/codemodder/codemods/RemoveRedundantVariableCreationCodemod.java
> +            final Expression expression = objectCreationExpr.clone();
@nahsra I tried doing it this way:

```
if (lastStmt instanceof ReturnStmt returnStmt) {
              returnStmt.setExpression(expression);
            }
            if (lastStmt instanceof ThrowStmt throwStmt) {
              throwStmt.setExpression(expression);
            }
```

but my test fails 😟

2023-12-05 00:45 UTC, carlosu7 commented on core-codemods/src/main/java/io/codemodder/codemods/RemoveRedundantVariableCreationCodemod.java
> +            final Expression expression = objectCreationExpr.clone();
updated xd

2023-12-05 00:50 UTC, nahsra requested changes

2023-12-05 00:50 UTC, nahsra commented on core-codemods/src/main/java/io/codemodder/codemods/RemoveRedundantVariableCreationCodemod.java
> +        if (lastStmt instanceof ThrowStmt throwStmt) {
Should this be `else if`? I feel like we should have an `else` block here too, in case its something unexpected (and which we shouldn't call the `remove()`:
```
if(isReturn) {
 ...
} else if(isThrow) {
 ...
} else {
 // something weird happened, don't remove
}
```

Am I crazy?

2023-12-05 01:10 UTC, carlosu7 commented on core-codemods/src/main/java/io/codemodder/codemods/RemoveRedundantVariableCreationCodemod.java
> +        if (lastStmt instanceof ThrowStmt throwStmt) {
nop, something weird could happen

2023-12-05 03:00 UTC, nahsra approved these changes

2023-12-05 03:58 UTC, merged