Sonar codemod to Replace the "@Controller" annotation by "@RestController" and remove all "@ResponseBody" annotations.
pixee/codemodder-java pull request #255
Opened 2023-12-05 23:14 UTC by carlosu7

Given example: https://sonarcloud.io/project/issues?cleanCodeAttributeCategories=CONSISTENT&resolved=false&id=nahsra_WebGoat_10_23&open=AYvtrj4zLCzGLicz7AqC&tab=code

Sonar rule Reference: https://rules.sonarsource.com/java/RSPEC-5361/

2023-12-05 23:14 UTC, carlosu7 commented on core-codemods/src/main/resources/io/codemodder/codemods/HardenRestControllerCodemod/description.md
> +// TODO
@nahsra 🙏

2023-12-06 01:24 UTC, nahsra requested changes

2023-12-06 01:24 UTC, nahsra commented on core-codemods/src/main/java/io/codemodder/codemods/HardenRestControllerCodemod.java
> +    executionPriority = CodemodExecutionPriority.HIGH)
Do the other Sonar codemods have `CodemodExecutionPriority.HIGH` as well?

2023-12-06 01:24 UTC, nahsra commented on core-codemods/src/main/java/io/codemodder/codemods/HardenRestControllerCodemod.java
> +public final class HardenRestControllerCodemod
`Harden` doesn't feel right to me as class name. How about `SimplifyRestControllerAnnotationsCodemod`?

2023-12-06 01:24 UTC, nahsra commented on core-codemods/src/main/resources/io/codemodder/codemods/HardenRestControllerCodemod/description.md
> +// TODO
I am happy to write a description, but you can add a simplified example for our changes.

2023-12-07 21:48 UTC, nahsra requested changes

2023-12-07 21:48 UTC, nahsra commented on core-codemods/src/main/resources/io/codemodder/codemods/SimplifyRestControllerAnnotationsCodemod/description.md
> +      public void example() {
Let's make this something realistic, `public AccountDetails viewAccount()`?

2023-12-07 21:48 UTC, nahsra commented on core-codemods/src/main/resources/io/codemodder/codemods/SimplifyRestControllerAnnotationsCodemod/report.json
> +  "references" : [
Um, this URL isn't right, right? Have we made this mistake anywhere else?

2023-12-07 21:48 UTC, nahsra commented on core-codemods/src/main/resources/io/codemodder/codemods/SimplifyRestControllerAnnotationsCodemod/description.md
> +// TODO
```
This change makes it harder for developers to make a mistake when writing REST controllers in Spring. By marking the top level type with `@RestController`, it is now assumed that all the methods within it will return a Java object representing the response body. Thus, there is no need to specify, for each method, the `@ResponseBody` annotation. 
```

2023-12-08 02:06 UTC, carlosu7 commented on core-codemods/src/main/resources/io/codemodder/codemods/SimplifyRestControllerAnnotationsCodemod/report.json
> +  "references" : [
this is the only one wrong

2023-12-09 00:14 UTC, nahsra approved these changes

2023-12-09 00:16 UTC, merged