Sonar codemod for defining a constant instead of duplicating literal string n times
pixee/codemodder-java pull request #262
Opened 2023-12-14 06:51 UTC by carlosu7

example https://sonarcloud.io/project/issues?open=AYu2g5It97lOFaqEjR1c&id=pixee_codemodder-java

reference https://rules.sonarsource.com/java/RSPEC-1192/

2023-12-14 06:51 UTC, carlosu7 commented on core-codemods/src/main/resources/io/codemodder/codemods/DefineConstantForLiteralCodemod/description.md
> +
I will add the code example soon , could you help me with the description 🙏

2023-12-14 06:54 UTC, carlosu7 commented on plugins/codemodder-plugin-sonar/src/main/java/io/codemodder/providers/sonar/api/Issue.java
> +  private List<Flow> flows;
I have added the `flows` property since inside this array we can retrieve the locations of the other duplicated strings as you can read in the sonar report file `core-codemods/src/test/resources/define-constant-for-duplicate-literal-s1192/sonar-issues.json`

2023-12-14 06:57 UTC, carlosu7 commented on core-codemods/src/main/java/io/codemodder/codemods/DefineConstantForLiteralCodemod.java
> +    return stringLiteralExpr.getValue().toUpperCase().concat("_CONSTANT");
not sure if this is the constant naming convention we want to follow...

also if would like to check if there are other variables to avoid duplicated variable names

2023-12-14 22:00 UTC, nahsra requested changes
Aside from the comments left, we need more test cases to verify the behavior is what we want when we're operating on interfaces, inner classes, etc.

2023-12-14 22:00 UTC, nahsra commented on core-codemods/src/main/java/io/codemodder/codemods/DefineConstantForLiteralCodemod.java
> +    return stringLiteralExpr.getValue().toUpperCase().concat("_CONSTANT");
Gosh, no -- that's ugly. Let's create something smarter here. Feel free to design something.

Also, we need something smart here to check if there's also something with that name anywhere so we don't collide.

2023-12-14 22:00 UTC, nahsra commented on core-codemods/src/main/java/io/codemodder/codemods/DefineConstantForLiteralCodemod.java
> +    return expectedDups == numberOfDuplications;
This method is trying to do too many things at the same time. 

It's trying to count if the number of expected occurrences is what we expect. But, it's also changing them at the same time. So, what happens if we change 3, but we expected 4? We'll return `false` but we _did_ make changes -- we can only return `true` if we make changes.

Maybe we can break this into a few different methods? Collect, check the number, then invoke a second method to make the changes, if the numbers have to match up.

Why do the numbers have to match up, by the way?

2023-12-14 22:00 UTC, nahsra commented on core-codemods/src/main/java/io/codemodder/codemods/DefineConstantForLiteralCodemod.java
> +
Will this be a common utility for codemods? If so, should it be in a common utility class?  I also think the name of it is wrong. It seems like it's "creating", not "finding". Let's re-think the method name.

2023-12-15 17:29 UTC, carlosu7 commented on core-codemods/src/main/java/io/codemodder/codemods/DefineConstantForLiteralCodemod.java
> +    return expectedDups == numberOfDuplications;
i was thinking that changes were only applied if the `onIssueFound` method only return true, but now i see that it doesn't

2024-01-12 15:51 UTC, nahsra requested changes
I added a few tweaks here, but while I do some more thinking about the API design, I think we should think about how to verify this more strongly, given how often this will make a relatively invasive change. This combination of unit and integration tests is a good start, but before releasing it into the wild, I do feel like we need more integration tests.

Can we go run this on a few different open source projects, and use them as test cases? Can we find an OSS project that finds several (maybe dozens?) of instances of this, so we can stress test our logic here? I want to make sure not only that it works, and we don't break anything, but that our naming strategy generally produces what we want.

2024-01-12 15:51 UTC, nahsra commented on core-codemods/src/main/java/io/codemodder/codemods/VariableCollector.java
> +final class VariableCollector extends VoidVisitorAdapter<Void> {
Why does this need to be an adapter? Why can't we call `compilationUnit.findAll(VariableDeclarator.class)`?

Also, should we also avoid collisions with method names?  Should we be searching for any `NodeWithSimpleName`?

2024-01-12 15:51 UTC, nahsra commented on core-codemods/src/main/resources/io/codemodder/codemods/DefineConstantForLiteralCodemod/description.md
> +
You've got this

2024-01-12 15:51 UTC, nahsra commented on core-codemods/src/main/resources/io/codemodder/codemods/DefineConstantForLiteralCodemod/report.json
> +  "references" : [
Can we find another official-ish source?

2024-01-12 15:51 UTC, nahsra commented on core-codemods/src/test/java/io/codemodder/codemods/ConstantNameStringGeneratorTest.java
> +
`final`

2024-01-12 15:51 UTC, nahsra commented on core-codemods/src/main/java/io/codemodder/codemods/CreateConstantForLiteral.java
> +class CreateConstantForLiteral extends DefineConstantForLiteral {
`final`

2024-01-16 15:24 UTC, nahsra commented on core-codemods/src/main/java/io/codemodder/codemods/DefineConstantForLiteral.java
> +
Need JavaDoc all over these new types. It's complicated enough to warrant.

2024-01-16 15:25 UTC, nahsra commented on core-codemods/src/main/java/io/codemodder/codemods/DefineConstantForLiteral.java
> +
`execute()` is such a generic name I would only expect it on a generic type, something like `Runnable` or `Thread`. What is this doing?

2024-01-16 15:26 UTC, nahsra commented on core-codemods/src/main/java/io/codemodder/codemods/DefineConstantForLiteralCodemod.java
> +    DefineConstantForLiteral defineConstantForLiteral;
This pattern suggests we probably need to compose this codemod into multiple smaller codemods, but I'm not sure that's worth the distraction at the moment.

2024-01-17 02:13 UTC, nahsra approved these changes

2024-01-17 02:13 UTC, nahsra commented on core-codemods/src/main/java/io/codemodder/codemods/CreateConstantForLiteral.java
> + * A class that extends DefineConstantForLiteral and specializes in creating new constants for
Is it always String literals?

2024-01-17 02:13 UTC, nahsra commented on core-codemods/src/main/java/io/codemodder/codemods/UseExistingConstantForLiteral.java
> +  protected void defineConstant(final String constantName) {
If this comment is true, it's not a great abstract design. We only have 2 subclasses and one of them doesn't need it.

2024-01-17 02:13 UTC, nahsra commented on core-codemods/src/main/resources/io/codemodder/codemods/DefineConstantForLiteralCodemod/report.json
> +  "references" : [
This still stands?

2024-01-17 02:13 UTC, nahsra commented on core-codemods/src/test/java/io/codemodder/codemods/DefineConstantForLiteralCodemodTest3.java
> +
Ahh, I see we added these directories because we need different `sonar-issues.json` files? We could cram them into one `sonar-issues.json` file, but I suppose this is better test isolation.

2024-01-17 02:13 UTC, nahsra commented on core-codemods/src/main/java/io/codemodder/codemods/DefineConstantForLiteralCodemod.java
> +    DefineConstantForLiteral defineConstantForLiteral;
This is why composition is usually preferred to inheritance!

2024-01-17 17:50 UTC, carlosu7 commented on core-codemods/src/main/java/io/codemodder/codemods/CreateConstantForLiteral.java
> + * A class that extends DefineConstantForLiteral and specializes in creating new constants for
yes

2024-01-17 18:12 UTC, carlosu7 commented on core-codemods/src/main/resources/io/codemodder/codemods/DefineConstantForLiteralCodemod/report.json
> +  "references" : [
I didn't find any good official source other than sonarsource

2024-01-19 23:33 UTC, merged