Sonar codemod to replace `Stream.collect(Collectors.toList())` with `Stream.toList()`
pixee/codemodder-java pull request #264
Opened 2023-12-14 20:50 UTC by carlosu7

Reference https://rules.sonarsource.com/java/RSPEC-6204/

Example: https://sonarcloud.io/project/issues?open=AYu2g5Hn97lOFaqEjR0v&id=pixee_codemodder-java

2023-12-14 21:51 UTC, nahsra requested changes
This can only be enabled if we can confirm that we are on Java... 17, maybe? The `toList()` method is new. Can you add that? I believe that was something that we get from `MavenProvider`. If we can't determine the version, we should take no action.

We should make whatever changes we can to support this codemod, because I have other changes I also want to make for other rules that require know that it's at least a certain Java version.

2023-12-14 21:52 UTC, nahsra commented on core-codemods/src/main/resources/io/codemodder/codemods/ReplaceStreamCollectorsToListCodemod/description.md
> +-        linesAffected.stream().map(CodemodChange::from).collect(Collectors.toList());
This is a confusing change example because it's very specific to us, can we create a more "Hello, World" example?

2023-12-14 21:54 UTC, nahsra commented on core-codemods/src/main/resources/io/codemodder/codemods/ReplaceStreamCollectorsToListCodemod/description.md
> +TODO
```
This change modernizes the a stream's `List` creation to be driven from the simple, and more readable `Stream#toList()` method. 
```

You should make the toList a link to the Javaoc for it.

2023-12-15 00:00 UTC, carlosu7 commented
> This can only be enabled if we can confirm that we are on Java... 17, maybe? The `toList()` method is new. Can you add that? I believe that was something that we get from `MavenProvider`. If we can't determine the version, we should take no action.
> 
> We should make whatever changes we can to support this codemod, because I have other changes I also want to make for other rules that require know that it's at least a certain Java version.

I have sonarlint in my IDE and checked if the rule is raised for a java project prior to 16 and it is not being triggered.

2023-12-15 01:23 UTC, nahsra approved these changes

2023-12-15 01:24 UTC, nahsra commented
Nice! Looks like we can count on Sonar to verify that for us.

2023-12-15 04:54 UTC, merged