Sonar codemod for removing unused private method codemod
pixee/codemodder-java pull request #266
Opened 2023-12-18 23:32 UTC by carlosu7

example https://sonarcloud.io/project/issues?fileUuids=AYvtrjqILCzGLicz7AZw&resolved=false&types=CODE_SMELL&id=nahsra_WebGoat_10_23&open=AYx_HQhaOVCWpCEOKEAO

reference: https://rules.sonarsource.com/java/RSPEC-1144/

2023-12-18 23:38 UTC, carlosu7 commented on core-codemods/src/main/resources/io/codemodder/codemods/RemoveUnusedPrivateMethodCodemod/description.md
> +TODO
🙏

2023-12-18 23:53 UTC, nahsra requested changes

2023-12-18 23:53 UTC, nahsra commented on core-codemods/src/main/java/io/codemodder/codemods/RemoveUnusedPrivateMethodCodemod.java
> +    reviewGuidance = ReviewGuidance.MERGE_WITHOUT_REVIEW,
`MERGE_WITHOUT_REVIEW` seems pretty strong -- I would say `MERGE_AFTER_REVIEW`. I am expecting there could be the _very_ rare issue with serialization, reflection, or some other crazy silly thing.

2023-12-18 23:53 UTC, nahsra commented on core-codemods/src/main/resources/io/codemodder/codemods/RemoveUnusedPrivateMethodCodemod/description.md
> +
```
This change removes unused `private` methods. Dead code can cause confusion and increase the mental load of maintainers. It can increase your maintenance burden as you have to keep that unused code compiling when you make sweeping changes to the APIs used within the method.
```

2023-12-18 23:53 UTC, nahsra commented on core-codemods/src/main/java/io/codemodder/codemods/RemoveUnusedPrivateMethodCodemod.java
> +/** A codemod for removing unused private method. */
`methods` not `method`

2023-12-18 23:53 UTC, nahsra commented on core-codemods/src/main/resources/io/codemodder/codemods/RemoveUnusedPrivateMethodCodemod/report.json
> +  "references" : [
Can you add this reference? I like this one:

https://understandlegacycode.com/blog/delete-unused-code/

2023-12-19 03:12 UTC, nahsra approved these changes

2023-12-19 05:41 UTC, merged