Declare variable separate line codemod
pixee/codemodder-java pull request #268
Opened 2023-12-20 05:38 UTC by carlosu7

2023-12-20 20:33 UTC, carlosu7 commented
Tests are failing after adding sonar codemods to DefaultCodemods, I'm going to check them

2023-12-20 20:41 UTC, carlosu7 commented on core-codemods/src/main/resources/io/codemodder/codemods/DeclareVariableOnSeparateLineCodemod/description.md
> +TODO
🙏 
📿

2023-12-20 20:45 UTC, carlosu7 commented on plugins/codemodder-plugin-sonar/src/main/java/io/codemodder/providers/sonar/SonarPluginJavaParserChanger.java
> +    if (issues == null || issues.isEmpty()) {
Fix for NPE that was thrown at `:core-codemods:intTest` tests after adding sonar codemods to DefaultCodemods

2023-12-21 00:39 UTC, nahsra requested changes

2023-12-21 00:39 UTC, nahsra commented on core-codemods/src/main/java/io/codemodder/codemods/DeclareVariableOnSeparateLineCodemod.java
> +    } catch (final NullPointerException nullPointerException) {
Having to catch a `NullPointerException` is usually a code smell of bad design. Also, exceptions are generally named `e`.

2023-12-21 00:39 UTC, nahsra commented on core-codemods/src/main/java/io/codemodder/codemods/DeclareVariableOnSeparateLineCodemod.java
> +
This looks like it should be a `record` as it stands, but it feels like we created this type so we could have generics. I think you can have a generic method without having a generic type.

We see this pattern commonly in deserializing libraries, offering APIs like this:
```
public static <T> T fromXml(Class<T> clazz, String xml) {
```

I don't think there's much reason for this to be a type.

2023-12-21 00:39 UTC, nahsra commented on core-codemods/src/main/java/io/codemodder/codemods/DeclareVariableOnSeparateLineCodemod.java
> +    List<T> retrieveNewNodes() {
Should this be `private`? Same with constructor?

2023-12-21 00:39 UTC, nahsra commented on core-codemods/src/main/resources/io/codemodder/codemods/DeclareVariableOnSeparateLineCodemod/report.json
> +  "summary" : "Declared variable on separate line (Sonar)",
I think this should be `Split variable declarations into their own statements`

2023-12-21 00:39 UTC, nahsra commented on plugins/codemodder-plugin-sonar/src/main/java/io/codemodder/providers/sonar/SonarPluginJavaParserChanger.java
> +    if (issues == null || issues.isEmpty()) {
This is weird. This feels like a code smell too. Why is this `null`? Is that the intended design?

2023-12-21 00:39 UTC, nahsra commented on core-codemods/src/main/java/io/codemodder/codemods/DeclareVariableOnSeparateLineCodemod.java
> +  private static final class NodesInserter<T extends Node> {
Without JavaDoc, it's unclear what the purpose of this is?

2023-12-21 00:39 UTC, nahsra commented on core-codemods/src/main/java/io/codemodder/codemods/DeclareVariableOnSeparateLineCodemod.java
> +
This validation can all be part of a `record` constructor thing.

2023-12-21 00:39 UTC, nahsra commented on core-codemods/src/main/java/io/codemodder/codemods/DeclareVariableOnSeparateLineCodemod.java
> +    final NodeList<Modifier> modifiers = getModifiers(parentNode, isFieldDeclaration);
I think this method should be really short. Like 10 lines. We should have _one_ place where we check `if` the issue is for a `FieldDeclaration`. From that point forward, we can use some kind of abstraction (`abstract` class? Two smaller methods?) - but this method is far too complex.

2023-12-21 00:39 UTC, nahsra commented on core-codemods/src/main/java/io/codemodder/codemods/DeclareVariableOnSeparateLineCodemod.java
> +    for (VariableDeclarator inlineVariable : inlineVariables) {
Repeated `if` checks for the same info are making this code very hard to review and keep straight.

2023-12-21 00:39 UTC, nahsra commented on core-codemods/src/main/resources/io/codemodder/codemods/DeclareVariableOnSeparateLineCodemod/description.md
> +TODO
```
This change splits variable assignments onto their own lines. [Many](https://wiki.sei.cmu.edu/confluence/display/java/DCL52-J.+Do+not+declare+more+than+one+variable+per+declaration) [sources](https://rules.sonarsource.com/java/RSPEC-1659/) [believe](https://dart.dev/tools/linter-rules/avoid_multiple_declarations_per_line) it is easier to review code where the variables are separate statements on their own individual line. 
```

You can also add the CMU link in this text to the references.

2024-01-02 23:30 UTC, nahsra commented on core-codemods/src/main/java/io/codemodder/codemods/DeclareVariableOnSeparateLineForVariableDeclarationExpr.java
> +
Need to be `public`? Should be `abstract` or `final`?

2024-01-02 23:38 UTC, nahsra requested changes

2024-01-02 23:38 UTC, nahsra commented on core-codemods/src/main/java/io/codemodder/codemods/DeclareVariableOnSeparateLineForVariableDeclarationExpr.java
> +    super(parentNode);
Should add an invariant check here by putting `Objects.requireNonNull()` around `parentNode`

2024-01-02 23:38 UTC, nahsra commented on core-codemods/src/main/java/io/codemodder/codemods/DeclareVariableOnSeparateLineForFieldDeclaration.java
> +  /**
When possible we should add JavaDoc links when discussing types, like in this example we would write:  `{@link ClassOrInterfaceDeclaration}`

2024-01-02 23:38 UTC, nahsra commented on core-codemods/src/main/java/io/codemodder/codemods/DeclareVariableOnSeparateLineForFieldDeclaration.java
> +    if (classOrInterfaceDeclarationOptional.isPresent()
If this condition is `false`, wouldn't the caller want to know that? So that the codemod can return `false`?

2024-01-02 23:38 UTC, nahsra commented on core-codemods/src/main/java/io/codemodder/codemods/DeclareVariableOnSeparateLine.java
> +public abstract class DeclareVariableOnSeparateLine {
Does this need to be `public`? I can see an argument for this to support fixing this discovered by other tools.

2024-01-02 23:38 UTC, nahsra commented on core-codemods/src/main/java/io/codemodder/codemods/DeclareVariableOnSeparateLine.java
> +    this.parentNode = parentNode;
`requireNonNull()`

2024-01-02 23:38 UTC, nahsra commented on core-codemods/src/main/java/io/codemodder/codemods/DeclareVariableOnSeparateLine.java
> +  protected abstract List<Node> createVariableNodesToAdd(List<VariableDeclarator> inlineVariables);
Need some JavaDoc here

2024-01-02 23:38 UTC, nahsra commented on core-codemods/src/main/java/io/codemodder/codemods/DeclareVariableOnSeparateLine.java
> +  protected abstract void addNewNodesToParentNode(List<Node> nodesToAdd);
Need JavaDoc here

2024-01-02 23:38 UTC, nahsra commented on core-codemods/src/main/java/io/codemodder/codemods/DeclareVariableOnSeparateLine.java
> +  protected static final class NodesInserter {
What is the point of this being in a nested `protected static final`, rather than another member method. Is it meant to be called by other types? The design feels a bit random, but maybe I'm missing something.

2024-01-02 23:38 UTC, nahsra commented on core-codemods/src/main/java/io/codemodder/codemods/DeclareVariableOnSeparateLineForFieldDeclaration.java
> +
`final`?

2024-01-02 23:38 UTC, nahsra commented on core-codemods/src/main/java/io/codemodder/codemods/DeclareVariableOnSeparateLineForFieldDeclaration.java
> +    this.fieldDeclaration = (FieldDeclaration) parentNode;
`requireNonNull()`

2024-01-04 02:39 UTC, nahsra requested changes

2024-01-04 02:39 UTC, nahsra commented on core-codemods/src/main/java/io/codemodder/codemods/DeclareVariableOnSeparateLine.java
> +  static <T> List<T> mergeNodes(
Based on the JavaDoc, I would think we call this `insertNodesAfter()`, or something like that.

2024-01-04 02:39 UTC, nahsra commented on core-codemods/src/main/java/io/codemodder/codemods/DeclareVariableOnSeparateLineForFieldDeclaration.java
> +    this.fieldDeclaration = (FieldDeclaration) Objects.requireNonNull(parentNode);
It's weird that this is being cast in the constructor, the constructor should be taking this as a `FieldDeclaration`.

2024-01-04 05:56 UTC, nahsra approved these changes

2024-01-04 17:24 UTC, merged