Sonar codemod for removing block of commented-out lines of code
pixee/codemodder-java pull request #269
Opened 2023-12-21 00:31 UTC by carlosu7

2023-12-21 00:33 UTC, carlosu7 commented on core-codemods/src/test/resources/remove-commented-code-s125/Test.java.after
> +      // return 0;
this comment is not being reported by sonnar, that's why it is expected to be here in the changed file

sonar report of the file: https://sonarcloud.io/project/issues?fileUuids=AYvtrjqJLCzGLicz7Abr&resolved=false&types=CODE_SMELL&id=nahsra_WebGoat_10_23

2024-01-02 18:43 UTC, carlosu7 commented on core-codemods/src/main/java/io/codemodder/codemods/RemoveCommentedCodeCodemod.java
> +  private static final RegionNodeMatcher regionNodeMatcher =
specific region node matcher written for this codemod since javaparser and sonarcloud differ on the column

2024-01-02 19:10 UTC, carlosu7 commented on core-codemods/src/main/resources/io/codemodder/codemods/RemoveCommentedCodeCodemod/description.md
> +TODO
🥺 🙏

2024-01-02 23:24 UTC, nahsra commented on core-codemods/src/main/resources/io/codemodder/codemods/RemoveCommentedCodeCodemod/description.md
> +TODO
give it a shot, i believe in you

2024-01-02 23:26 UTC, nahsra commented on core-codemods/src/main/java/io/codemodder/codemods/RemoveCommentedCodeCodemod.java
> +  private static final RegionNodeMatcher regionNodeMatcher =
There should be a big, detailed JavaDoc on this.

2024-01-02 23:26 UTC, nahsra commented on core-codemods/src/main/resources/io/codemodder/codemods/RemoveCommentedCodeCodemod/report.json
> +  "references" : [
We should try to find another unbiased, expert source.

2024-01-02 23:27 UTC, nahsra requested changes
Great start!

2024-01-04 02:31 UTC, nahsra requested changes

2024-01-04 02:31 UTC, nahsra commented on plugins/codemodder-plugin-sonar/src/main/java/io/codemodder/providers/sonar/SonarPluginJavaParserChanger.java
I see what you're trying to do here. A few things:

1. There's no need for this to be `public`, right? Just `protected`?
2. This type hierarchy tries hard to favor composition over inheritance, but this is just straight up inheritance. Just like we invented `RegionNodeMatcher` to help codemods define how they could customize their behavior, it seems like we may need a new type so we can match that new philosophy. Maybe a new `NodeCollector` type? 

Please consider Effective Java Chapter 16 -- Favoring Composition over Inheritance, discussed here by the author: https://blogs.oracle.com/javamagazine/post/java-inheritance-composition.

3. The name is...not quite right. With that name, I'm expecting it to collect a flattened `List` of all the nodes in the AST. I think this name problem goes away when you fix the issue above anyway.

2024-01-04 05:54 UTC, nahsra approved these changes

2024-01-04 17:38 UTC, merged