Update CodeTFChange to include explicit DiffSide
pixee/codemodder-java pull request #281
Opened 2024-02-05 22:09 UTC by drdavella

2024-02-05 22:09 UTC, drdavella commented on framework/codemodder-base/src/main/java/io/codemodder/DefaultCodemodExecutor.java
> +            CodeTFDiffSide.LEFT,
This preserves the existing behavior wrt to platform integration. But we may want to differentiate and/or switch to `RIGHT` going forward.

2024-02-05 22:54 UTC, nahsra requested changes

2024-02-05 22:54 UTC, nahsra commented on plugins/codemodder-plugin-maven/src/main/java/io/codemodder/plugins/maven/CodeTFGenerator.java
> +    // Use RIGHT side as the diff side for now, as we are only adding dependencies.
I appreciate you making this change _at all_, but any chance we can add a test assertion that the Maven code is using `RIGHT`?

I could only look at this for a minute, but I think such a test would be in `MavenProviderTest.java`. Maybe we add a new line 247: that looks something like this:

```
assertThat(changes.get(0).getChanges().get(0).getSide()).isEqualTo(CodeTFDiffSide.RIGHT);
```

2024-02-06 02:22 UTC, drdavella commented on plugins/codemodder-plugin-maven/src/main/java/io/codemodder/plugins/maven/CodeTFGenerator.java
> +    // Use RIGHT side as the diff side for now, as we are only adding dependencies.
Done. That was a pretty good breadcrumb, thanks 😅

2024-02-06 02:36 UTC, nahsra approved these changes

2024-02-06 19:07 UTC, ryandens approved these changes

2024-02-12 19:12 UTC, merged