New conditions to not apply SwitchLiteralFirstComparisonsCodemod
pixee/codemodder-java pull request #305
Opened 2024-03-13 15:36 UTC by carlosu7

This codemod will not be executed if: 
1. Variable was previously initialized to a not null value 
2. Variable has a previous not null assertion 
3. Variable has a `@NotNull` / `@Nonnull `annotation

Related issue https://github.com/pixee/codemodder-java/issues/298

2024-03-13 15:52 UTC, nahsra requested changes
Amazing start! Let's try to use streams more, and add a new test.

2024-03-13 15:52 UTC, nahsra commented on core-codemods/src/main/java/io/codemodder/codemods/SwitchLiteralFirstComparisonsCodemod.java
> +    }
All of these functions returning `List` should return a `List.copyOf()`, since there's no reason for them to be mutable

2024-03-13 15:52 UTC, nahsra commented on core-codemods/src/main/java/io/codemodder/codemods/SwitchLiteralFirstComparisonsCodemod.java
> +
There's a lot of repetitive list creation here in this file. Can we refactor these methods to use streams?

2024-03-13 15:52 UTC, nahsra commented on core-codemods/src/main/java/io/codemodder/codemods/SwitchLiteralFirstComparisonsCodemod.java
> +
Rather than use `null`, can we use `Optional`?

2024-03-14 20:58 UTC, nahsra commented on core-codemods/src/intTest/java/io/codemodder/integration/WebGoat822Test.java
Well this is surprising -- can you see which ones we no longer find/fix?

2024-03-15 04:30 UTC, nahsra commented on core-codemods/src/main/java/io/codemodder/codemods/SwitchLiteralFirstComparisonsCodemod.java
> -    return false;
You could make this a little simpler/less nested/slightly less complex with:
```
.filter(declarator -> declarator.getName().equals(targetName))
.filter(declarator -> isPreviousNodeBefore(targetName, declarator.getName())

.anyMatch(declarator -> declarator.getInitializer()
                            .map(expr -> !(expr instanceof NullLiteralExpr))
                            .orElse(false));
```

I think there's some other improvements here I could make but I'm tired

2024-03-15 04:40 UTC, carlosu7 commented on core-codemods/src/intTest/java/io/codemodder/integration/WebGoat822Test.java
To check differences, I just ran this integration test with this codemod

Before this update, these are the files that are being modified
<img width="1056" alt="Screenshot 2024-03-14 at 10 17 10 p m" src="https://github.com/pixee/codemodder-java/assets/14047435/120b436e-5d96-4f79-b617-1804d7cf5a0b">


But now, the modified files are the following:
<img width="1056" alt="Screenshot 2024-03-14 at 10 17 51 p m" src="https://github.com/pixee/codemodder-java/assets/14047435/1f7c65e7-8368-4907-bf74-27fade6c4a43">


The 6 files that are no longer modified are:
[webgoat-lessons/cross-site-scripting/src/main/java/org/owasp/webgoat/xss/CrossSiteScriptingLesson3.java](https://github.com/WebGoat/WebGoat/blob/e75cfbeb110e3d3a2ca3c8fee2754992d89c419d/webgoat-lessons/cross-site-scripting/src/main/java/org/owasp/webgoat/xss/CrossSiteScriptingLesson3.java)

[webgoat-lessons/crypto/src/main/java/org/owasp/webgoat/crypto/SecureDefaultsAssignment.java](https://github.com/WebGoat/WebGoat/blob/e75cfbeb110e3d3a2ca3c8fee2754992d89c419d/webgoat-lessons/crypto/src/main/java/org/owasp/webgoat/crypto/SecureDefaultsAssignment.java)

[webgoat-lessons/crypto/src/main/java/org/owasp/webgoat/crypto/XOREncodingAssignment.java](https://github.com/WebGoat/WebGoat/blob/e75cfbeb110e3d3a2ca3c8fee2754992d89c419d/webgoat-lessons/crypto/src/main/java/org/owasp/webgoat/crypto/XOREncodingAssignment.java)

[webgoat-lessons/csrf/src/main/java/org/owasp/webgoat/csrf/CSRFGetFlag.java](https://github.com/WebGoat/WebGoat/blob/e75cfbeb110e3d3a2ca3c8fee2754992d89c419d/webgoat-lessons/csrf/src/main/java/org/owasp/webgoat/csrf/CSRFGetFlag.java)

[webgoat-lessons/password-reset/src/main/java/org/owasp/webgoat/password_reset/ResetLinkAssignment.java](https://github.com/WebGoat/WebGoat/blob/e75cfbeb110e3d3a2ca3c8fee2754992d89c419d/webgoat-lessons/password-reset/src/main/java/org/owasp/webgoat/password_reset/ResetLinkAssignment.java)

[webwolf/src/main/java/org/owasp/webwolf/WebWolf.java](https://github.com/WebGoat/WebGoat/blob/e75cfbeb110e3d3a2ca3c8fee2754992d89c419d/webwolf/src/main/java/org/owasp/webwolf/WebWolf.java)

2024-03-15 04:57 UTC, carlosu7 commented on core-codemods/src/intTest/java/io/codemodder/integration/WebGoat822Test.java
@nahsra now that I'm checking, for the test case of :
[webwolf/src/main/java/org/owasp/webwolf/WebWolf.java](https://github.com/WebGoat/WebGoat/blob/e75cfbeb110e3d3a2ca3c8fee2754992d89c419d/webwolf/src/main/java/org/owasp/webwolf/WebWolf.java)
Former changes:
```
-        if (null==fileEncoding || !fileEncoding.equals("UTF-8")) {
+        if (null==fileEncoding || !"UTF-8".equals(fileEncoding)) {
```
`fileEncoding` is being initialized [here](https://github.com/WebGoat/WebGoat/blob/e75cfbeb110e3d3a2ca3c8fee2754992d89c419d/webwolf/src/main/java/org/owasp/webwolf/WebWolf.java#L53)

variable is initialized but it can throw a NPE (in this case it doesn't apply because of the previous `null==fileEncoding` assertion)

2024-03-15 05:07 UTC, nahsra approved these changes

2024-03-15 13:24 UTC, merged

2024-03-15 14:08 UTC, nahsra commented
Wait, I looked at one of the WebGoat samples, and I think we might be wrong.

See the `fistNameElement` 
example: https://github.com/WebGoat/WebGoat/blob/e75cfbeb110e3d3a2ca3c8fee2754992d89c419d/webgoat-lessons/cross-site-scripting/src/main/java/org/owasp/webgoat/xss/CrossSiteScriptingLesson3.java

Why don't we harden this case? On line 52 it gets assigned:

```
String fistNameElement = doc.select("body > table > tbody > tr:nth-child(1) > td:nth-child(2)").first().text();
```

But we have no guarantee this isn't `null`, are we being to aggressive now? I don't think we have any proof this has been initialized to a not-null value?