XStream hardening codemod should use `denyTypesByWildcard()` when possible instead of `registerConverter()`
pixee/codemodder-java pull request #322
Opened 2024-03-28 19:31 UTC by carlosu7

Now this codemod checks if the xstream dependency version is equal or greater than `1.4.8` to use `denyTypesByWildcard()`. Arguments that will take this method will be provided by `io.github.pixee.security.UnwantedTypes`.

To check xstream dependency version, dependencies will be sent in `CodemodInvocationContext `

Issue https://github.com/pixee/codemodder-java/issues/301

2024-03-28 19:35 UTC, carlosu7 commented on core-codemods/src/main/java/io/codemodder/codemods/HardenXStreamCodemod.java
> +  private static boolean useDenyTypes;
This static boolean var will be updated at https://github.com/pixee/codemodder-java/pull/323 but due to large number of files, i decided to open another PR

2024-03-28 20:27 UTC, nahsra requested changes

2024-03-28 20:27 UTC, nahsra commented on core-codemods/src/test/java/io/codemodder/codemods/HardenXStreamCodemodTest.java
> +final class HardenXStreamCodemodTest_denyTypes implements CodemodTestMixin {}
Should still follow Java norms for file name, e.g. `HardenXStreamCodemodTestWithDenyTypes`.

2024-03-28 20:27 UTC, nahsra commented on framework/codemodder-base/src/main/java/io/codemodder/DefaultCodemodInvocationContext.java
> +    Collection<DependencyGAV> dependecies)
typo: `dependencies`

2024-03-28 20:27 UTC, nahsra commented on framework/codemodder-base/src/main/java/io/codemodder/DefaultCodemodInvocationContext.java
> +    Objects.requireNonNull(dependecies);
Same typo

2024-03-28 20:27 UTC, nahsra commented on framework/codemodder-base/src/main/java/io/codemodder/ProjectProvider.java
> +  Collection<DependencyGAV> getAllDependencies(Path projectDir, Path file);
JavaDoc

2024-03-28 20:27 UTC, nahsra commented on framework/codemodder-testutils/src/main/java/io/codemodder/testutils/HardenXStreamCodemodTestProjectProvider.java
> +
Seems like this could be `final` and not `public`, or just a `mock()` even. Shouldn't we have one for:

* 1.4.7
* 1.4.9
* and one with an unparseable version, to see how it handles the failure case

2024-03-28 20:27 UTC, nahsra commented on plugins/codemodder-plugin-maven/src/main/java/io/codemodder/plugins/maven/DefaultPOMDependencyUpdater.java
> +    return pomOperator.getAllFoundDependencies();
This class is called `Updater`, do we need a different design, or different name? It seems like this should come from the `ProjectProvider` 🤔

2024-03-28 20:27 UTC, nahsra commented on plugins/codemodder-plugin-maven/src/main/java/io/codemodder/plugins/maven/POMDependencyUpdater.java
> +
JavaDoc (if we decide to keep this)

2024-03-29 13:41 UTC, nahsra requested changes

2024-03-29 13:41 UTC, nahsra commented on core-codemods/src/main/java/io/codemodder/codemods/HardenXStreamCodemod.java
> +    } catch (final Exception e) {
Should we log something here?

2024-03-29 13:41 UTC, nahsra commented on core-codemods/src/main/java/io/codemodder/codemods/HardenXStreamCodemod.java
> +  private static boolean useDenyTypes;
So I'll take another quick look once the other PR is merged.

2024-03-29 13:41 UTC, nahsra commented on core-codemods/src/test/java/io/codemodder/codemods/HardenXStreamCodemodTestProjectProvider.java
> +  public static class XStreamSameDependencyVersion implements ProjectProvider {
These inner classes don't need to be `public`, right?

2024-03-29 13:41 UTC, nahsra commented on core-codemods/src/test/resources/harden-xstream-denyTypes/Test.java.after
> +    public void deserializeObject_CallsAllowTypes(XStream xstream) throws IOException, ClassNotFoundException {
Method name should be `DenyTypes`

2024-03-29 13:41 UTC, nahsra commented on framework/codemodder-testutils/src/main/java/io/codemodder/testutils/Metadata.java
> +  Class<?>[] projectProviders() default {};
Should this be `Class<? extends ProjectProvider>`?

2024-03-29 13:41 UTC, nahsra commented on framework/codemodder-testutils/src/main/java/io/codemodder/testutils/Metadata.java
> +
Another shot at this comment:

"Some codemods change their behavior based on the context of the app -- like which versions of libraries are present. If you want to simulate specific contextual conditions related to dependencies, you can add a customized provider here."

2024-03-29 17:12 UTC, nahsra commented
I'm probably missing it, but where is the test that confirms we use the `HardeningConverter` Test before/after when using <=1.4.7?

2024-03-29 18:37 UTC, carlosu7 commented on core-codemods/src/test/java/io/codemodder/codemods/HardenXStreamCodemodTestProjectProvider.java
> +  public static class XStreamSameDependencyVersion implements ProjectProvider {
they need to be public because it is being used by `@Metadata` which is in another folder (codemodder-testutils) and this class HardenXStreamCodemodTestProjectProvider is in core-codemods

2024-03-29 18:45 UTC, carlosu7 commented
> I'm probably missing it, but where is the test that confirms we use the `HardeningConverter` Test before/after when using <=1.4.7?

there it is, I renamed it to HardenXStreamCodemodTestHardeningConverter

2024-03-31 18:57 UTC, nahsra approved these changes

2024-04-01 16:41 UTC, merged