Refactor  `JavaParserChanger` onResultFound and onIssueFound to return an object
pixee/codemodder-java pull request #323
Opened 2024-03-28 19:34 UTC by carlosu7

This refactor was done in order to provide a `ChangesResult` object that will contain a boolean that indicates if changes were done by the codemod and the list of dependencies added by it

2024-03-28 20:44 UTC, nahsra requested changes
Some small changes to consider!

2024-03-28 20:44 UTC, nahsra commented on framework/codemodder-base/src/main/java/io/codemodder/javaparser/ChangesResult.java
> +public class ChangesResult {
I believe this this should be an `interface` (named `ChangeResults`).

It should offer instances like:

```java
public interface ChangesResult {

   // the methods

  // easy instances to re-use
  ChangeResults noChanges = new DefaultChangeResults(false, List.of());

  // a default builder
 static ChangeResults from(boolean changesApplied, List dependenciesRequired) {
  ...
 }
```

Also we should null check the dependencies because I hate having to deal with null values.

2024-03-28 20:44 UTC, nahsra commented on framework/codemodder-base/src/main/java/io/codemodder/javaparser/ChangesResult.java
> +  public boolean areChangesApplied() {
This prompts some thinking. The _reason_ changes are not applied may be interesting to the caller, but maybe we don't need to expose this yet. I'd love to know "not changed because shape was unexpected" or "not changed because I failed".

2024-03-28 20:44 UTC, nahsra commented on framework/codemodder-base/src/main/java/io/codemodder/javaparser/ChangesResult.java
> +  public static ChangesResult changesApplied(final List<DependencyGAV> dependenciesRequired) {
What do you think about renaming this to `changesAppliedWith()`?

2024-03-29 05:48 UTC, carlosu7 commented on framework/codemodder-base/src/main/java/io/codemodder/javaparser/ChangesResult.java
> +  public boolean areChangesApplied() {
a new string field `reason` to be used by the caller when no changes were applied?

should we create another ticket for it?

2024-03-29 13:27 UTC, nahsra commented on framework/codemodder-base/src/main/java/io/codemodder/javaparser/DefaultChangesResult.java
> +
`final`

2024-03-29 13:28 UTC, nahsra approved these changes

2024-03-29 18:47 UTC, merged