Improvements to the parameterizer codemods
pixee/codemodder-java pull request #324
Opened 2024-03-29 13:31 UTC by andrecsilva

Changed the testing conditions for the SQL/HQL parameterizer codemod to make changes.

- Weakened conditions for making changes. The algorithm will make changes to variables that are used after declaration. This may cause some wrong changes to be made, but those are rare.
- Refactored `LinearizeStringExpression` out of `QueryParameterizer`. This may help to write other injection based codemods.
- Added transformations for removing empty string concatenations and unused variables. Those are meant to be used as a cleanup step to the parameterizer codemods, but the last one is not currently in use due to a (just discovered) JavaParser bug. This means the transformation may leave some unused variables in the code.

These changes make it possible to fix the following examples listed in #303.
```
org.owasp.webgoat.lessons.sqlinjection.advanced.SqlInjectionLesson6a:74
org.owasp.webgoat.lessons.sqlinjection.introduction.SqlInjectionLesson5a:67
org.owasp.webgoat.lessons.sqlinjection.introduction.SqlInjectionLesson8:78
org.owasp.webgoat.lessons.sqlinjection.introduction.SqlInjectionLesson9:76
```

2024-03-29 16:30 UTC, nahsra requested changes

2024-03-29 16:30 UTC, nahsra commented on framework/codemodder-base/src/main/java/io/codemodder/ast/ASTs.java
>    public static List<NameExpr> findAllReferences(final LocalVariableDeclaration localDeclaration) {
Remove printlns?

2024-03-29 16:30 UTC, nahsra commented on framework/codemodder-base/src/main/java/io/codemodder/ast/LinearizedStringExpression.java
> +   */
All other args are `final` in this type so we should probably match

2024-03-29 16:30 UTC, nahsra commented on framework/codemodder-base/src/test/java/io/codemodder/ast/ASTsTest.java
> +
Awesome!

2024-03-29 16:30 UTC, nahsra commented on core-codemods/src/main/java/io/codemodder/codemods/HQLParameterizationCodemod.java
> +            .collect(Collectors.toList());
This seems like too broad of a scope to apply this `removeEmptyString`. Can we limit to the `BlockStmt` or method in which we found this? I'm worried about making unrelated changes and confusing the user.

2024-04-01 14:03 UTC, nahsra commented on core-codemods/src/main/java/io/codemodder/codemods/SQLParameterizerCodemod.java
> +      // TODO hits a bug with javaparser, where adding nodes won't result in the correct children
What is the TODO here? Should we create a ticket for ourselves to fix this once the upstream bug is fixed?

2024-04-01 14:05 UTC, nahsra commented on core-codemods/src/main/java/io/codemodder/codemods/SQLParameterizerCodemod.java
> +      var maybeMethodDecl = methodCallExpr.findAncestor(MethodDeclaration.class);
This could be a `ConstructorDeclaration` too, right?

2024-04-01 16:03 UTC, andrecsilva commented on core-codemods/src/main/java/io/codemodder/codemods/SQLParameterizerCodemod.java
> +      // TODO hits a bug with javaparser, where adding nodes won't result in the correct children
The TODO is mostly there to remember to uncomment this once the issue is solved or we find a workaround. I'll create both a ticket here and upstream for this bug. For now, I'm investigating a bit more to gather better feedback or to solve it myself.

2024-04-01 16:03 UTC, andrecsilva commented on core-codemods/src/main/java/io/codemodder/codemods/SQLParameterizerCodemod.java
> +      var maybeMethodDecl = methodCallExpr.findAncestor(MethodDeclaration.class);
Good call. I'll add it.

2024-04-01 17:11 UTC, nahsra requested changes

2024-04-01 17:11 UTC, nahsra commented on framework/codemodder-base/src/test/java/io/codemodder/ast/TestUtils.java
> +  static CompilationUnit parseCode(final String code) {
We should use `JavaParserFactory` instead.

2024-04-01 17:11 UTC, nahsra commented on framework/codemodder-base/src/test/java/io/codemodder/ast/TestUtils.java
> +
Can we scope down the type name here? The scope of it is so broad.

2024-04-01 19:57 UTC, merged