Added resource leak transform and general codemod
pixee/codemodder-java pull request #339
Opened 2024-04-09 12:59 UTC by andrecsilva

Added a new resource leak transform and general codemod

- Removed CodeQL dependency for ResourceLeakFixer and left it available as a general transform.
- Added new resource leak codemod independent of CodeQL. This may conflict with the resource leak codemods if both are available, producing more changes than necessary.
- Added ResourceLeakFixer transform to PreventFileWriterLeakWithFilesCodemod. Closes #304.

You may notice the changes to the PreventFileWriterLeakWithFilesCodemod test files. This is due to a newly discovered issue. Refer to #338.

2024-04-09 14:20 UTC, nahsra requested changes
How do you like this plan:
* Take the new codemod out of `DefaultCodemods`
* Create tickets for the various improvements discussed here
* Ship this PR 
* Work follow-on tickets
* Add back to `DefaultCodemods`

That way, we get to keep moving forward, improve incrementally, and don't have to give our users changes they may have formatting objections towards.

2024-04-09 14:20 UTC, nahsra commented on core-codemods/src/intTest/java/io/codemodder/integration/WebGoat822Test.java
>            "src/test/resources/webgoat_v8.2.2_codeql.sarif",
This could be solved by making the CodeQL one run with `CodemodExecutionPriority.LOW`, maybe?

2024-04-09 14:20 UTC, nahsra commented on core-codemods/src/main/java/io/codemodder/codemods/ResourceLeakCodemod.java
> +public final class ResourceLeakCodemod extends JavaParserChanger {
I think this should be `CodemodExecutionPriority.LOW`.

2024-04-09 14:20 UTC, nahsra commented on core-codemods/src/main/java/io/codemodder/codemods/ResourceLeakFixer.java
>     * Detects if a {@link Expression} detected by CodeQL that creates a leaking resource is fixable.
Did these assumptions change, because we're not using a more general utility that doesn't guarantee the same things by this point?

2024-04-09 14:20 UTC, nahsra commented on core-codemods/src/main/java/io/codemodder/codemods/ResourceLeakFixer.java
> +
I love how easy it is to express these constraints now.

2024-04-09 14:20 UTC, nahsra commented on core-codemods/src/test/resources/resource-leak/Test.java.before
> +
Can we call this `noFixMethod` like the others so we know the intention of the test code?

2024-04-09 14:20 UTC, nahsra commented on core-codemods/src/test/resources/resource-leak/Test.java.after
> +    try (FileReader resource1 = new FileReader("~/test.txt");
I think `resource1` is fine for now, but I think we need to create a follow-up ticket for calling it `fileReader` (whatever the type is, at least).

2024-04-09 14:20 UTC, nahsra commented on core-codemods/src/test/resources/prevent-filewriter-leak-with-nio/Test.java.after
> -        Writer change2 = Files.newBufferedWriter(f.toPath());
This test makes me wonder if we should have try-with-resources with multiple files. Consider the example [here](https://stackoverflow.com/questions/47175526/try-with-multiple-resource-in-java):

```
try (
        java.util.zip.ZipFile zf =
             new java.util.zip.ZipFile(zipFileName);
        java.io.BufferedWriter writer = 
            java.nio.file.Files.newBufferedWriter(outputFilePath, charset)
    ) {
        // Enumerate each entry
        for (java.util.Enumeration entries =
                                zf.entries(); entries.hasMoreElements();) {
            // Get the entry name and write it to the output file
            String newLine = System.getProperty("line.separator");
            String zipEntryName =
                 ((java.util.zip.ZipEntry)entries.nextElement()).getName() +
                 newLine;
            writer.write(zipEntryName, 0, zipEntryName.length());
        }
    }
```

Is this worth chasing down? Should it be added to the scope of this change, or added later?

2024-04-09 14:20 UTC, nahsra commented
Also, this PR and the changes are _awesome_!

2024-04-09 14:23 UTC, andrecsilva commented on core-codemods/src/test/resources/prevent-filewriter-leak-with-nio/Test.java.after
> -        Writer change2 = Files.newBufferedWriter(f.toPath());
You mean having a try with multiple resources instead of two consecutive ones? I can work on a transform to do that.

2024-04-09 14:37 UTC, andrecsilva commented on core-codemods/src/main/java/io/codemodder/codemods/ResourceLeakFixer.java
>     * Detects if a {@link Expression} detected by CodeQL that creates a leaking resource is fixable.
(1) and (3) are being tested by the new `isClosedOrEscapes`. This test was already in place for dependent resources, so I just added it to the resource we are trying to fix.
(2) Is not being tested. This decision was deliberate. This means that, for example, if you have a `Connection` object that is already being closed, it will still try to close a `Statement` object that it spawns. The reason being that most examples and advice I've encountered recommended to close those object separately.
Generally speaking, this won't cause any trouble since `close()` is usually idempotent (it is not required to, but strongly encouraged, see https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html). I've yet to test one that is not on the JAVA API. I can also include a test for this property if you want to be on the safe side.

2024-04-09 14:45 UTC, nahsra commented on core-codemods/src/main/java/io/codemodder/codemods/ResourceLeakCodemod.java
> +public final class ResourceLeakCodemod extends JavaParserChanger {
Let me defend why. I say `LOW` because I'd like CodeQL to fix it "first", then I'd love any codemods that want to orchestrate this ability into themselves be able to do it next, then this as a last resort.

2024-04-09 14:47 UTC, nahsra commented on core-codemods/src/main/java/io/codemodder/codemods/ResourceLeakCodemod.java
> +      final CodemodInvocationContext context, final CompilationUnit cu) {
This will be an extremely expensive codemod to execute as it will force every file to be visited, and every `Expression` to be evaluated. 

I think we need a Semgrep pattern to detect reasonable starting points that can be confirmed more thoroughly by AST-inspecting code.

2024-04-09 14:50 UTC, nahsra commented on core-codemods/src/main/java/io/codemodder/codemods/ResourceLeakFixer.java
> +              .filter("java.nio.file.Files"::equals);
The `startsWith("new")` makes me a bit nervous here as it doesn't feel future safe.

2024-04-09 14:52 UTC, nahsra commented on core-codemods/src/main/java/io/codemodder/codemods/ResourceLeakCodemod.java
> +      final CodemodInvocationContext context, final CompilationUnit cu) {
This is a guess, but I think it's not that much to test. Again, maybe we should add it to another ticket, and make sure we check that ticket off before we add to `DefaultCodemods`.

2024-04-09 14:52 UTC, nahsra commented on core-codemods/src/main/java/io/codemodder/codemods/ResourceLeakFixer.java
>     * Detects if a {@link Expression} detected by CodeQL that creates a leaking resource is fixable.
I think this is right.

2024-04-09 14:56 UTC, andrecsilva commented on core-codemods/src/main/java/io/codemodder/codemods/ResourceLeakCodemod.java
> +      final CodemodInvocationContext context, final CompilationUnit cu) {
The only reason it visits `Expression` is that we cannot express sum types easily. Notice that the first thing it does is test if the given expression is `ObjectCreationExpression` or `MethodCallExpression`. After that the first check is if it is a `AutoCloseable` type. I think those two check are fast and restrictive enough to nip most visits without spending much.

2024-04-09 14:57 UTC, andrecsilva commented on core-codemods/src/main/java/io/codemodder/codemods/ResourceLeakFixer.java
> +              .filter("java.nio.file.Files"::equals);
True enough, I will change it to check against a list of current resource creation methods in `Files`.

2024-04-12 18:31 UTC, nahsra approved these changes

2024-04-12 18:31 UTC, merged