Populate detectionTool metadata for CodeQL codemods
pixee/codemodder-java pull request #347
Opened 2024-04-11 22:28 UTC by carlosu7

Implement `FixOnlyCodeChanger` for CodeQL codemods

2024-04-12 00:42 UTC, nahsra requested changes

2024-04-12 00:42 UTC, nahsra commented on core-codemods/src/main/java/io/codemodder/codemods/MavenSecureURLCodemod.java
> +        linesAffected.stream()
Is `file.toString()` the ID? Shouldn't we be getting a GUID out of the SARIF `Result` object or something? This ID represents the tool vendor's ID for that finding.

2024-04-12 00:42 UTC, nahsra commented on plugins/codemodder-plugin-codeql/src/main/java/io/codemodder/providers/sarif/codeql/CodeQLSarifJavaParserChanger.java
> + * Provides foundational functionality for modifying Java code using JavaParser based on findings
Comment copied and incorrect

2024-04-15 20:48 UTC, carlosu7 commented on core-codemods/src/main/java/io/codemodder/codemods/MavenSecureURLCodemod.java
> +        linesAffected.stream()
@nahsra currently, i'm not seeing how the results are related to the affected lines of the xmlChange because the list of results right now is not taken in consideration and i think it should now be considered if we want to link the result guid to the affected line

but since the current test only has 1 affected line and the result guid is null, i'm not sure how to link the guid and the affected line

2024-04-15 22:32 UTC, nahsra requested changes

2024-04-15 22:32 UTC, nahsra commented on core-codemods/src/main/java/io/codemodder/codemods/MavenSecureURLCodemod.java
> +public final class MavenSecureURLCodemod extends SarifPluginRawFileChanger
Should this extend a new `CodeQLSarifPluginRawFileChanger` type?

2024-04-15 22:32 UTC, nahsra commented on core-codemods/src/main/java/io/codemodder/codemods/MavenSecureURLCodemod.java
> +        linesAffected.stream()
Is the correlation GUID also null? If not, we should use that.

2024-04-15 22:32 UTC, nahsra commented on plugins/codemodder-plugin-codeql/src/main/java/io/codemodder/providers/sarif/codeql/CodeQLSarifJavaParserChanger.java
> + */
Still a typo here, it says "Semgrep"...

2024-04-16 01:03 UTC, closed without merging