refactor sonar issues json path to list
pixee/codemodder-java pull request #365
Opened 2024-05-07 23:00 UTC by carlosu7

2024-05-08 19:29 UTC, drdavella requested changes
Looks good overall. Even though `--sonar-hotspots-json` is just a pass-thru without implementation I think we should also update the help message to indicate a comma-separated input.

2024-05-08 19:29 UTC, drdavella commented on framework/codemodder-base/src/main/java/io/codemodder/CodemodLoader.java
> +      final List<Path> sonarIssuesJsonFile,
Change variable name here and below
```suggestion
      final List<Path> sonarIssuesJsonFiles,
```

2024-05-08 19:29 UTC, drdavella commented on framework/codemodder-base/src/main/java/io/codemodder/CLI.java
> +      List<Path> sarifFiles = sarifs != null ? sarifs.stream().map(Path::of).toList() : List.of();
Could this be factored out into a function to share?

2024-05-09 13:57 UTC, drdavella commented on plugins/codemodder-plugin-sonar/src/main/java/io/codemodder/providers/sonar/SonarModule.java
> +    if (issuesFiles != null) {
This code makes sense to me but I also want to be careful that we don't introduce any regressions here. Would you be able to add a unit test or do you feel like this is sufficiently covered by existing tests?

2024-05-09 23:52 UTC, carlosu7 commented on plugins/codemodder-plugin-sonar/src/main/java/io/codemodder/providers/sonar/SonarModule.java
> +    if (issuesFiles != null) {
@drdavella 
When we run a codemod test that is not a sonar codemod, this sonar module is being executed because all modules (defectdojo, semgrep, codeql, sonar, etc) are being configured at CodemodLoader.java. So, in when the non-sonar codemod test is being executed, this sonar module handles the empty/null issuesFiles because they're not required for that codemod (defectdojo, semgrep, etc).

So yes, this case is already covered.

2024-05-10 00:18 UTC, carlosu7 commented on plugins/codemodder-plugin-sonar/src/main/java/io/codemodder/providers/sonar/SonarModule.java
> +    if (issuesFiles != null) {
@drdavella In this commit https://github.com/pixee/codemodder-java/pull/365/commits/be04cc0fdfc8ed7ec6ddb763d765e804ac8da868 I have updated our tests to support multiple sonar issues json files and refactor one existing sonar test

2024-05-13 14:51 UTC, drdavella commented on framework/codemodder-testutils/src/main/java/io/codemodder/testutils/CodemodTestMixin.java
> +      Path defaultPath = testResourceDir.resolve("sonar-issues.json");
Sorry, I thought I left this comment before but I don't see it. Shouldn't it be this now?
```suggestion
      Path defaultPath = testResourceDir.resolve("sonar-issues_1.json");
```

2024-05-13 18:52 UTC, carlosu7 commented on framework/codemodder-testutils/src/main/java/io/codemodder/testutils/CodemodTestMixin.java
> +      Path defaultPath = testResourceDir.resolve("sonar-issues.json");
@drdavella no, default sonar issues filename remains the same as it previously was, otherwise, i will have to rename all other sonar codemod test json files 
<img width="469" alt="Screenshot 2024-05-13 at 12 51 17 p m" src="https://github.com/pixee/codemodder-java/assets/14047435/1c529923-233d-45bb-a1f3-a41184a6db86">

2024-05-13 19:01 UTC, drdavella commented on framework/codemodder-testutils/src/main/java/io/codemodder/testutils/CodemodTestMixin.java
> +      Path defaultPath = testResourceDir.resolve("sonar-issues.json");
Oh okay, I'm sorry. I missed that the one you renamed was for a specific test.

2024-05-13 19:22 UTC, carlosu7 commented on framework/codemodder-testutils/src/main/java/io/codemodder/testutils/CodemodTestMixin.java
> +      Path defaultPath = testResourceDir.resolve("sonar-issues.json");
yes

2024-05-13 19:22 UTC, merged