Internal module for sonar-api-models
pixee/codemodder-java pull request #372
Opened 2024-06-10 21:09 UTC by carlosu7

Use triage models that are currently in pixee-platform

2024-06-10 22:47 UTC, ryandens requested changes

2024-06-10 22:47 UTC, ryandens commented on core-codemods/src/test/resources/test-applications/replace-apache-defaulthttpclient/src/main/java/ai/pixee/integration/replaceapachedefaulthttpclient/ReplaceApacheDefaulthttpclientApplication.java
> +package io.pixee.integration.replaceapachedefaulthttpclient;
is there a reason we chose to rename this package? we do own `io.pixee` but we currently don't namespace any code there - either ai.pixee or io.codemodder

2024-06-10 22:47 UTC, ryandens commented on sonar-api-model/build.gradle.kts
> +    id("maven-publish")
```suggestion
    id("io.codemodder.java-library")
    id("io.codemodder.maven-publish")
```

we have convention plugins for these which helps standardize our usage inside this project

2024-06-10 22:47 UTC, ryandens commented on sonar-api-model/build.gradle.kts
> +
```suggestion

description = "Library with API models for data from Sonar tools"
```

Maven Central requires a description for every module that's published

2024-06-11 19:27 UTC, nahsra approved these changes

2024-06-11 20:10 UTC, ryandens requested changes

2024-06-11 20:10 UTC, ryandens commented on sonar-api-model/build.gradle.kts
> +    id("io.codemodder.java-library")
this is missing the recommended plugin 
```suggestion
    id("io.codemodder.java-library")
    id("io.codemodder.maven-publish")
```

2024-06-11 20:21 UTC, ryandens approved these changes

2024-06-11 20:50 UTC, merged