✨ New Sonar Remediation Codemod for Unsafe Reflection
pixee/codemodder-java pull request #390
Opened 2024-06-20 21:25 UTC by gilday

Remediates Sonar findings of type java:S2658.

Does not yet cover edge-cases, but I'd like to get some feedback on the happy path while I work on those edge cases.

2024-06-20 21:35 UTC, gilday commented on framework/codemodder-testutils/src/main/java/io/codemodder/testutils/CodemodTestMixin.java
> +    Assertions.assertThat(after).hasSameTextualContentAs(expected, StandardCharsets.UTF_8);
Getting much better diff in the test failure message with this.

2024-06-20 21:52 UTC, nahsra requested changes

2024-06-20 21:52 UTC, nahsra commented on core-codemods/src/main/java/io/codemodder/codemods/UnsafeReflectionRemediationCodemod.java
> +public final class UnsafeReflectionRemediationCodemod
Ditch `SonarPluginJavaParserChanger` in favor of the new `SonarRemediatingJavaParserChanger`. The new pattern makes it much easier to report CodeTF stuff that's important for where we're headed (aligning fixes to tool findings downstream.) See `SonarSQLInjectionCodemod for an example`. 

All we lose is a little boilerplate, but we get much better reporting outcomes.

2024-06-20 21:52 UTC, nahsra commented on framework/codemodder-testutils/src/main/java/io/codemodder/testutils/CodemodTestMixin.java
> -    assertThat(transformedJavaCode, equalTo(expectedCode));
Ironically that's why I was using hamcrest -- the assertj APIs I was using were not giving me nice IntelliJ "Click to see.." diffs. Does this fix that?

2024-06-21 01:38 UTC, gilday commented on framework/codemodder-testutils/src/main/java/io/codemodder/testutils/CodemodTestMixin.java
> -    assertThat(transformedJavaCode, equalTo(expectedCode));
I'm not getting IntelliJ's "Click to see diff" in neither Hamcrest nor AssertJ. When you saw that in IntelliJ, were you using the IntelliJ JUnit runner (vs the "delegate to Gradle" runner)? fwiw I tried [fixing this feature for the Gradle runner in IntelliJ last year](https://github.com/JetBrains/intellij-community/commit/b9c612ac25618478c6d29813ef4c2446eb47f6c7), but I guess the fix was brittle, because it's no longer working for me.

Without that IntelliJ feature helping out, the Hamcrest errors are unintelligible. AssertJ has the diffing built-in, so I don't need to rely on the IntelliJ regex finding its match.

2024-06-24 15:32 UTC, nahsra commented
I'm picking up this PR.

2024-06-24 17:35 UTC, nahsra approved these changes

2024-06-24 17:36 UTC, merged