⬆️ Upgrade GPT 3.5 Turbo Model
pixee/codemodder-java pull request #398
Opened 2024-06-24 15:11 UTC by gilday

gpt-3.5-turbo-0613 has been removed, so replace it with gpt-3.5-turbo-0125.

Also, add a model for GPT models that colocates model-specific logic such as token counting.

/close #work

2024-06-24 15:13 UTC, gilday commented on plugins/codemodder-plugin-llm/src/main/java/io/codemodder/plugins/llm/Model.java
Added this interface in addition to the `StandardModel` enum, so that downstream projects may add their own model if needed (vs being constrained to the enum definition in `codemodder-java`).

2024-06-24 18:56 UTC, gilday commented on core-codemods/src/test/resources/logback-test.xml
This helped me understand why tests were failing.

2024-06-24 19:13 UTC, nahsra approved these changes
This should help  a lot!

2024-06-24 19:40 UTC, gilday commented
nvm, I'm still getting flakey tests. I need to keep working on this.

2024-06-25 20:47 UTC, nahsra commented on plugins/codemodder-plugin-llm/src/main/java/io/codemodder/plugins/llm/SarifToLLMForBinaryVerificationAndFixingCodemod.java
>              .temperature(temperature)
I know we're kind of throwing darts here -- I'd throw this change out if it's not obviously helping, as it could affect other codemods performing well already.

2024-06-25 21:00 UTC, nahsra requested changes
Consider `top_p` change before merging.

2024-06-26 15:58 UTC, gilday commented on core-codemods/src/test/resources/log-failed-login/vulnerable/SaltedHashLoginModule.java.after
I changed this from "safe" to "vulnerable". I don't see a good reason why we shouldn't add the log statement here. It's the only place that has enough context to include the username in the audit log.

2024-06-26 15:58 UTC, gilday commented on core-codemods/src/test/resources/log-failed-login/vulnerable/MainFrame.java.after
> +                    Logger.getLogger(MainFrame.class.getName()).log(Level.INFO, "Failed login attempt for user: " + uname1);
We instruct the model to use the INFO level, so I don't know why this test insisted on WARNING level.

2024-06-26 16:04 UTC, gilday commented on core-codemods/src/test/java/io/codemodder/codemods/LogFailedLoginCodemodTest.java
> -@Disabled("codemod is in disrepair")
no amount of temperature and top_p changes are good enough to make this test stop flaking. I'm going to keep it disabled.

2024-06-26 19:44 UTC, nahsra approved these changes

2024-06-26 20:18 UTC, merged