Added support for chaning Statement object in assignments.
pixee/codemodder-java pull request #404
Opened 2024-06-26 16:30 UTC by andrecsilva

2024-06-26 20:14 UTC, nahsra requested changes

2024-06-26 20:14 UTC, nahsra commented on core-codemods/src/test/resources/sql-parameterizer/Test.java.before
> +
Typo: `singeAssigned`

2024-06-26 20:14 UTC, nahsra commented on core-codemods/src/test/resources/sql-parameterizer/Test.java.after
>    }
Tagging @ryandens for a second opinion. I think I wouldn't want to receive this change. It's too confusing, it's probably causing compiler warnings, etc.

2024-06-26 20:14 UTC, nahsra commented on core-codemods/src/test/resources/sql-parameterizer/Test.java.before
> +  }
Is the reason this code can't cleanly become a `PreparedStatement` because the history of `input` isn't known, and it might have SQL code in it?

2024-06-27 11:09 UTC, andrecsilva commented on core-codemods/src/test/resources/sql-parameterizer/Test.java.before
> +  }
Not really, the reason is simply because the changes are local and less prone to break something. For this restricted case, I can probably change it without breaking it. Will do so in the next commit.

2024-06-27 13:25 UTC, nahsra approved these changes

2024-06-27 13:25 UTC, merged