Added new codemod to fix SQL table injections
pixee/codemodder-java pull request #412
Opened 2024-07-04 14:09 UTC by andrecsilva

2024-07-05 13:42 UTC, nahsra requested changes
Great work. The logic of the change itself looks solid and I think it hits the mark! 

However, I think we need several changes to make this fit into a remediation-first mindset.

2024-07-05 14:58 UTC, andrecsilva commented on core-codemods/src/main/java/io/codemodder/codemods/SQLTableInjectionFilterCodemod.java
> +/** Filter table name parameters in SQL queries */
It is easier to develop a find-and-fix codemod since I don't need to grab sonar results for tests. Makes it faster to iterate if any problems arise (and they did).

Removing this would also means I need to refactor the tests into the sonar version. I say we keep it, since it's done.

2024-07-05 15:01 UTC, andrecsilva commented on core-codemods/src/main/java/io/codemodder/codemods/SQLTableInjectionFilterTransform.java
> +
Sorry, not sure what you mean here.

Do you think it should go into the `io.codemodder.codemod.util` package? Or do you want me to create a new `remediation.sql` package for this? In any case, the find-and-fix version needs visibility to this transform.

2024-07-05 16:50 UTC, nahsra commented on core-codemods/src/main/java/io/codemodder/codemods/DefaultCodemods.java
>          SQLParameterizerCodemod.class,
It should not be a default codemod.

2024-07-05 16:55 UTC, nahsra requested changes

2024-07-05 16:55 UTC, nahsra commented on core-codemods/src/main/java/io/codemodder/codemods/SQLTableInjectionFilterCodemod.java
> +/** Filter table name parameters in SQL queries */
We have a test case using Sonar JSON, so I don't see this a high maintenance burden. Many of our remediation-centered codemods also have this requirement.

The maintenance of unused code is higher than I think you give credit for -- I think we should delete it.

2024-07-05 16:55 UTC, nahsra commented on core-codemods/src/main/java/io/codemodder/codemods/SQLTableInjectionFilterTransform.java
> +  private static final String filterMethodName = "filterTable";
I think I like `sanitizeTableName` to start, but I'm going to send you more direction here.

2024-07-05 16:55 UTC, nahsra commented on core-codemods/src/main/java/io/codemodder/codemods/SQLTableInjectionFilterTransform.java
> +
This is exactly the kind of cost I was discussing above, where find+fix, because it's "already done", is creating a drag on development. I want, as much as possible, all logic for remediation in the `JavaParserSQLRemediationStrategy` types.

2024-07-08 10:27 UTC, andrecsilva commented on core-codemods/src/main/java/io/codemodder/codemods/SQLTableInjectionFilterCodemod.java
> +/** Filter table name parameters in SQL queries */
It's not high maintenance but high development cost. Obtaining the json is a manual process that involves: creating a PR -> committing a vulnerable file -> wait for scan -> curl the json -> manually modify the json/test (mostly the path).

Debugging issues with such a convoluted process is painstakingly slow. Specially compared with simply changing a file.
I've caught enough bugs from integrating a transformation into a full codemod to know how valuable those are.

It's fair if you want to delete the "regular" version of the codemod, but I would still rely on it for debugging/tweaks. Even if I need to make it from scratch again.

2024-07-08 12:22 UTC, andrecsilva commented on core-codemods/src/main/java/io/codemodder/codemods/SQLTableInjectionFilterTransform.java
> +  private static final String filterMethodName = "filterTable";
This is a validator, not a sanitizer. So I think `validateTableName` is a better choice.

2024-07-09 12:37 UTC, nahsra approved these changes

2024-07-09 12:42 UTC, merged