Adds per codemod Includes/Excludes
pixee/codemodder-java pull request #438
Opened 2024-08-16 12:26 UTC by andrecsilva

Codemods now have their own includes/excludes rules and a `supports` method.

Includes/Excludes rules are specified by `PathMatcher` patterns that are relative to the repository root.

Before running on a given file, codemods will now perform two checks: includes/excludes and `supports`. 

Codemod specific Includes/excludes check can be overridden by global configuration from the command line (i.e. with `--path-include` flag). 

`supports` checks the bare-minimum conditions that must be satisfied before the codemod attempts to run. For example, 
javaparser codemods will check if the file is a java file and sarif based codemods will check if there is any results for the file. 

Refactored some scattered file checks in codemods into the `supports` method. For example, the `VerbTamperingCodemod` will now check if the file is a `web.xml` file with the `supports` method instead. This has the benefit of avoiding the generation of empty codetf reports.

2024-08-16 17:41 UTC, nahsra requested changes

2024-08-16 17:41 UTC, nahsra commented on core-codemods/src/intTest/java/io/codemodder/integration/WebGoat822Test.java
> +  private static final String testPathIncludes =
Can we expose the actual values so both the tests and the CLI use the same values?

2024-08-16 17:41 UTC, nahsra commented on core-codemods/src/main/java/io/codemodder/codemods/DefaultCodemods.java
>          SonarXXECodemod.class,
Nice catch.

2024-08-16 17:41 UTC, nahsra commented on core-codemods/src/main/java/io/codemodder/codemods/VerbTamperingCodemod.java
> +  public boolean supports(Path file) {
Make all these new args `final`

2024-08-16 17:41 UTC, nahsra commented on framework/codemodder-base/src/main/java/io/codemodder/CompositeJavaParserChanger.java
> +  public IncludesExcludesPattern getIncludesExcludesPattern() {
This doesn't seem right, but not sure I have another proposal right now.

2024-08-16 17:41 UTC, nahsra commented on framework/codemodder-base/src/main/java/io/codemodder/IncludesExcludesPattern.java
> +    public Default(final Set<String> pathIncludes, final Set<String> pathExcludes) {
Can we make these null invariant?

E.g., `this.pathIncludes = Objects.requireNonNull(pathIncludes);`

2024-08-16 17:41 UTC, nahsra commented on framework/codemodder-base/src/main/java/io/codemodder/IncludesExcludesPattern.java
> +    public static IncludesExcludesPattern getInstance() {
Should this be `public`?

2024-08-16 17:41 UTC, nahsra commented on framework/codemodder-base/src/test/java/io/codemodder/CodemodLoaderTest.java
> +    @Override
In the most root interface (if you wanted), you could provide a `default` interface method that returns true.

2024-08-16 17:41 UTC, nahsra commented on framework/codemodder-base/src/test/java/io/codemodder/CodemodLoaderTest.java
> +    @Override
To prevent all these simple implementations.

2024-08-16 17:54 UTC, andrecsilva commented on framework/codemodder-base/src/test/java/io/codemodder/CodemodLoaderTest.java
> +    @Override
This was deliberate. Sarif and JavaParser based changers have reasonable defaults (sarif ones will check if the file is in the results and javaparser ones will check if it's a java file). 

Notice that all these are `RawFileChanger`s. Not having a default avoids creating codemods that inspect every file.

2024-08-16 18:00 UTC, andrecsilva commented on framework/codemodder-base/src/main/java/io/codemodder/CompositeJavaParserChanger.java
> +  public IncludesExcludesPattern getIncludesExcludesPattern() {
Ideally this would be an intersection of all the patterns. But I'm not sure we can calculate this with just the patterns themselves.

2024-08-19 10:20 UTC, andrecsilva commented on core-codemods/src/intTest/java/io/codemodder/integration/WebGoat822Test.java
> +  private static final String testPathIncludes =
CLI doesn't use these default includes anymore.

Do you still want these to be the default values for find-and-fix codemods? Right now every javaparser based one will only have `**.java` as its pattern.

2024-08-22 21:07 UTC, nahsra requested changes

2024-08-22 21:07 UTC, nahsra commented on framework/codemodder-base/src/main/java/io/codemodder/RawFileCodemodRunner.java
>      this.changer = Objects.requireNonNull(changer);
This is the only thing I don't like about this. This kind of subclass checking is a code smell of an architectural problem that will be hard to diagnose and fix later when it causes a problem.

2024-08-23 13:05 UTC, nahsra approved these changes

2024-08-23 13:26 UTC, merged