New Sonar SSRF codemod
pixee/codemodder-java pull request #449
Opened 2024-09-24 12:34 UTC by andrecsilva

2024-09-30 13:56 UTC, nahsra requested changes
We have a strategy for helping with this issue, even if it's not a complete resolution of all risk -- see  `SSRFCodemod`. This should use that same strategy. We may need to create an `SSRFRemediator`

2024-10-01 12:46 UTC, nahsra requested changes

2024-10-01 12:46 UTC, nahsra commented on core-codemods/src/main/java/io/codemodder/codemods/SonarSSRFCodemod.java
> +    id = "sonar:java/ssrf-s5144",
Shouldn't this be more like cursory review? Isn't there zero effective risk of this change?

2024-10-01 12:46 UTC, nahsra commented on core-codemods/src/main/java/io/codemodder/codemods/remediators/ssrf/DefaultSSRFRemediator.java
> +            // The type check below doesn't work
Let's pick one:

* fix the issue
* delete the comment and add a proper comment that this could be improved by further improving the type checking

We're not fans of commented code.

I must say I'm surprised the type checking doesn't resolve the type to either `RestTemplate` or the FQCN.

2024-10-01 12:46 UTC, nahsra commented on core-codemods/src/main/java/io/codemodder/codemods/remediators/ssrf/DefaultSSRFRemediator.java
> -        searcher.search(
I think it's not clear what this comment means, let's add a little more.

2024-10-01 13:18 UTC, andrecsilva commented on core-codemods/src/main/java/io/codemodder/codemods/remediators/ssrf/DefaultSSRFRemediator.java
> +            // The type check below doesn't work
It's an issue I've been observing with JavaParser's type resolver for quite some time. It works well with types from the Java API but struggles a bit with anything else.
I did a cursory investigation some time ago without much success. So, for now, I'll just comment it.

2024-10-01 13:18 UTC, andrecsilva commented on core-codemods/src/main/java/io/codemodder/codemods/SonarSSRFCodemod.java
> +    id = "sonar:java/ssrf-s5144",
Changed it to match `SSRFCodemod`

2024-10-01 13:32 UTC, nahsra approved these changes

2024-10-01 15:59 UTC, merged