Refactors remediators and adjacent classes
pixee/codemodder-java pull request #455
Opened 2024-10-11 13:47 UTC by andrecsilva

2024-10-11 20:19 UTC, nahsra commented
I like the direction! No other comments. Can we use the strangler pattern to move remediators over, one at a time?

2024-10-14 13:06 UTC, nahsra requested changes

2024-10-14 13:06 UTC, nahsra commented on framework/codemodder-base/src/main/java/io/codemodder/remediation/SuccessOrReason.java
> +public class SuccessOrReason {
Is this class meant to be extended? Make it `abstract`. If not, make it `final`. In truth, I would prefer an `interface` here. All `public` methods should also be JavaDoced.

2024-10-14 13:06 UTC, nahsra commented on framework/codemodder-base/src/main/java/io/codemodder/remediation/ModularRemediationStrategy.java
> +
`final` or `abstract`

2024-10-14 13:06 UTC, nahsra commented on framework/codemodder-base/src/main/java/io/codemodder/remediation/ModularRemediationStrategy.java
> +
+ JavaDoc

2024-10-14 13:06 UTC, nahsra commented on framework/codemodder-base/src/main/java/io/codemodder/remediation/DefaultLegacyFixCandidateSearcher.java
> +
Should we add a `@Deprecated` annotation here?

2024-10-14 13:06 UTC, nahsra commented on framework/codemodder-base/src/main/java/io/codemodder/remediation/jndiinjection/JNDIInjectionRemediator.java
> +public class JNDIInjectionRemediator<T> implements Remediator<T> {
These should still be interfaces with concrete implementations (e.g., `DefaultJNDIRemediator`) so they can be mocked for for testing. I know that we haven't invested much in testing the simple places in which they're used, but still...

2024-10-14 13:06 UTC, nahsra commented on framework/codemodder-base/src/main/java/io/codemodder/remediation/jndiinjection/JNDIFixContext.java
> +   */
This method has around 10 exit locations, but is only tested indirectly as part of other components. Does it have enough coverage?

2024-10-14 13:40 UTC, andrecsilva commented on framework/codemodder-base/src/main/java/io/codemodder/remediation/SuccessOrReason.java
> +public class SuccessOrReason {
This class is mostly a wrapper for the `Either` value inside. The reason for this class is ease of use and expression. It should be pretty clear what it means instead of a generic `Either` type.

With that said, it is not meant be extended or behave in any other way other than the current implementation.

2024-10-14 13:46 UTC, andrecsilva commented on framework/codemodder-base/src/main/java/io/codemodder/remediation/jndiinjection/JNDIFixContext.java
> +   */
Some of them should be covered in the `DefaultJNDIRemediatorStrategyTest`, but I'm not sure every exit is covered.

2024-10-14 16:09 UTC, andrecsilva commented on framework/codemodder-base/src/main/java/io/codemodder/remediation/jndiinjection/JNDIInjectionRemediator.java
> +public class JNDIInjectionRemediator<T> implements Remediator<T> {
Maybe I'm missing something, but I'm not sure I understand the point you're making entirely. 

The current class is the default implementation of the `Remediator` interface for JNDI. You could mock the `Remediator` if that's the problem.

I'm not sure creating a specific `JNDIInjectionRemediator` interface that is exactly, or largely, the same as the `Remediator` would accomplish.

Of course, I'm open to suggestions. Feel free to suggest a design that would accomplish what you mean.

2024-10-14 16:45 UTC, nahsra approved these changes

2024-10-14 16:48 UTC, merged