Converted remaining remediators to new API
pixee/codemodder-java pull request #462
Opened 2024-10-24 13:11 UTC by andrecsilva

2024-10-29 02:45 UTC, nahsra requested changes
Very cool! We're on the way. Before submitting a PR, make sure the easy stuff (`final`, `public`) etc. is right. 

I think there is a little more to the architecture to consider here, given the exposure of so many `public static` methods. Ideally we'd have no static methods that aren't generic utilities. Let's see if we can't iterate and make a solution that doesn't require them?

2024-10-29 02:45 UTC, nahsra commented on framework/codemodder-base/src/main/java/io/codemodder/remediation/FixCandidateSearcher.java
> -   * @param issuesForFile
It is a very cool idea to make this a mutable `List`. I wrestle with whether is a _good_ idea, because pure functions are easier to test and reason about. I am not inclined to stand in the way, just registering a concern.

2024-10-29 02:45 UTC, nahsra commented on framework/codemodder-base/src/main/java/io/codemodder/remediation/NodePositionMatcher.java
> +
JavaDoc

2024-10-29 02:45 UTC, nahsra commented on framework/codemodder-base/src/main/java/io/codemodder/remediation/WithoutScopePositionMatcher.java
> +  @Override
I think this type should be package-private, right? Does it need to be `public`? If it does, why is `getRange` not public?

2024-10-29 02:45 UTC, nahsra commented on framework/codemodder-base/src/main/java/io/codemodder/remediation/xxe/DocumentBuilderFactoryAndSAXParserAtCreationFixStrategy.java
> +
`final` + JavaDoc, and probably doesn't need to be `public`?

2024-10-29 02:45 UTC, nahsra commented on framework/codemodder-base/src/main/java/io/codemodder/remediation/xxe/SAXParserAtNewSPFixStrategy.java
> +
`final`

2024-10-29 02:45 UTC, nahsra commented on framework/codemodder-base/src/main/java/io/codemodder/remediation/xxe/XMLReaderAtParseFixStrategy.java
> +  public static boolean match(final Node node) {
All of these sister types expose this static method -- this is a smell we may need a different architecture?

2024-10-29 02:45 UTC, nahsra commented on framework/codemodder-base/src/main/java/io/codemodder/remediation/xxe/XXEIntermediateXMLStreamReaderFixStrategy.java
> +
`final` and not `public` I don't think -- applies to all of these.

2024-10-29 09:14 UTC, andrecsilva commented on framework/codemodder-base/src/main/java/io/codemodder/remediation/DefaultNodePositionMatcher.java
> +
`WithoutScopePositionMatcher` extends it.

2024-10-29 09:22 UTC, andrecsilva commented on framework/codemodder-base/src/main/java/io/codemodder/remediation/WithoutScopePositionMatcher.java
> +  @Override
`XXERemediator` uses it as parameter. And thus, some codemods (Sonar based ones, mostly) make use of it. Also some tests.

`getRange` is there mostly to reuse code from `DefaultNodePositionMatcher` and shouldn't be accessed as it is an implementation detail. I've made it `protected`.

2024-10-29 10:00 UTC, andrecsilva commented on framework/codemodder-base/src/main/java/io/codemodder/remediation/FixCandidateSearcher.java
> -   * @param issuesForFile
This is admittedly, a bit of a hack since I've failed to accommodate for the problem multiple searchers reporting the same issues as unfixed before working on converting the XXE Remediators, where the problem became very apparent.

I don't think this is that much of a problem wince you shouldn't be using the `FixCandidateSearcher` outside of `SearcherStrategyRemediator` now. But I see your point.

I'll think about a solution for this.

2024-10-29 10:09 UTC, andrecsilva commented on framework/codemodder-base/src/main/java/io/codemodder/remediation/xxe/XMLReaderAtParseFixStrategy.java
> +  public static boolean match(final Node node) {
Each of those `match` methods should be their own `FixCandidateSearcher`, but it gets very verbose.

I'll think on an abstraction to make this easier.

2024-10-31 13:00 UTC, nahsra approved these changes

2024-11-01 09:56 UTC, merged